export type AudienceLanguage = "ru" | "en";

export const operatorText = {
  ru: {
    topNote: "Симуляция аудитории",
    heroLineOne: "Как люди",
    heroLineTwo: "отреагируют",
    heroLineThree: "вашу идею?",
    heroLead: "Поймите, кому может быть полезна идея и что в ней важно.",
    languageButton: "English",
    languageButtonLabel: "Switch the stand to English",
    beginLabel: "Начать проверку идеи",
    ideaEyebrow: "01 / Начало проверки",
    ideaTitle: "Что проверяем?",
    sourceEyebrow: "02 / Открытые источники",
    sourceTitleOne: "Сначала слушаем",
    sourceTitleTwo: "рынок",
    sourceLead: "Ищем, кто и как уже говорит об этой проблеме.",
    sourcesFound: "ссылок найдено",
    scenarioSources: "найденных источников · сценарий",
    bundleLinks: "ссылок в сценарной подборке",
    pagesOpened: "страниц открыто",
    linkedSignals: "выводов со ссылками · сценарий",
    signalsConfirmed: "сигналов подтверждено",
    reviews: "Отзывы покупателей",
    reviewsScenario: "источники в сценарии",
    reviewsFound: "найденные страницы",
    communities: "Профессиональные сообщества",
    searchMaterials: "Поисковые материалы",
    recurringSignals: "Повторяющиеся сигналы",
    linkedToSources: "связаны с источниками",
    linkedFindings: "выводы в сценарии",
    sourceList: "Ссылки и статус страниц",
    pageOpened: "страница открыта",
    addressBlocked: "адрес заблокирован",
    sourceReference: "источник аналитического обзора",
    notChecked: "не проверена",
    verifiedQuotes: "Подтверждённые цитаты",
    searchNotFound: "Источники не найдены",
    searchReady: "Источники изучены",
    searchStopped: "Поиск остановился",
    checkingQuotes: "проверяем цитаты",
    linkingSignals: "Связываем сигналы с источниками и повторяющимися темами",
    connectingSearch: "Подключаем источники поиска",
    fallbackText: "Sonar не вернул проверяемые ссылки. Можно продолжить без открытых сигналов или выбрать другой готовый сценарий.",
    chooseAnotherScenario: "Выбрать другой сценарий",
    retrySourceProcessing: "Повторить обработку источников",
    retryPreparation: "Повторить подготовку",
    restart: "Начать заново",
    demoSourceFoot: "Счётчики показывают объём демонстрационного сценария; ниже приведены ссылки из аналитической подборки.",
    sourceFoot: "Связываем найденные упоминания с источниками и повторяющимися темами.",
    audienceEyebrow: "03 / Формируем аудиторию",
    audienceTitleOne: "Персоны",
    audienceTitleTwo: "под вашу идею",
    audienceLead: "Собираем аудиторию с учётом идеи и найденных рыночных сигналов.",
    buildingProfiles: "Формируем профили",
    selected: "выбрано",
    age: "Возраст",
    city: "Город",
    occupation: "Занятость",
    income: "Доход",
    habits: "Привычки",
    personaAria: "Открыть подробный профиль",
    matchingAudience: "Сопоставляем аудиторию с сигналами рынка…",
    clickForProfile: "Нажмите на карточку, чтобы открыть подробный профиль.",
    configureAudience: "Настроить состав и ограничения",
    audienceComposition: "Состав аудитории",
    done: "Готово",
    minimumProfiles: "Оставьте в аудитории не меньше пяти профилей.",
    readyScenarioNote: "Готовый сценарий · {count} персон · состав подобран из каталога 1 500 профилей",
    panelSize: "Размер панели",
    people: "персон",
    constraints: "Ограничения",
    optional: "Необязательно",
    interviewEyebrow: "05 / Синтетическое исследование",
    interviewTitleOne: "Собираем",
    interviewTitleTwo: "реакции аудитории",
    startingResearch: "Запускаем исследование",
    respondingInGroups: "Персоны отвечают в группах",
    connectingPersonas: "Подключаем персоны",
    mapEyebrow: "06 / Карта реакции",
    mapTitleOne: "Реакция",
    mapTitleTwo: "аудитории",
    problemAxis: "АКТУАЛЬНОСТЬ ПРОБЛЕМЫ",
    tryAxis: "ГОТОВНОСТЬ ПОПРОБОВАТЬ →",
    excluded: "НЕ УЧТЁН",
    excludedShort: "исключена",
    included: "учтена",
    problem: "Проблема",
    interest: "Интерес",
    tryIt: "Попробовать",
    noShortAnswer: "Короткого ответа нет",
    accounted: "Учтено",
    excludedCount: "исключено",
    answers: "ответов",
    insightsEyebrow: "07 / Выводы",
    insightsTitleOne: "Что говорит",
    insightsTitleTwo: "аудитория",
    problemThreshold: "оценили актуальность проблемы на 7/10 или выше",
    businessMismatch: "Выбраны бизнес-профили, хотя идея рассчитана на потребителей.",
    interestSeven: "интерес · оценка 7+",
    trySeven: "готовы попробовать · оценка 7+",
    responseCount: "Ответов собрано: {count}",
    resultReady: "Результат готов",
    continueStudying: "Продолжите",
    yourIdea: "изучать идею",
    scanQr: "Отсканируйте код, чтобы открыть подробный отчёт и сохранить результат.",
    openOnPhone: "Откройте результат<br />на телефоне",
    qrAlt: "QR-код отчёта",
    createQrPrompt: "Создайте QR-код, чтобы открыть и сохранить подробный отчёт.",
    newRun: "Новая проверка",
    stages: "Этапы проверки",
    loadingCampaign: "Загружаем кампанию",
    closeError: "Закрыть сообщение",
    genericError: "Не удалось выполнить действие. Попробуйте ещё раз.",
    unavailableCampaign: "Кампания сейчас недоступна.",
    openReadyScenarioError: "Не удалось открыть готовый сценарий. Попробуйте ещё раз.",
    audienceChanged: "Состав аудитории изменился. Вернитесь к его просмотру и запустите исследование ещё раз.",
    audienceUpdated: "Состав аудитории обновился. Проверьте выбранные группы и запустите исследование ещё раз.",
    confirmAudienceError: "Не удалось подтвердить аудиторию. Попробуйте ещё раз.",
    continueError: "Не удалось продолжить запуск. Попробуйте ещё раз.",
    retryError: "Не удалось повторить подготовку. Попробуйте ещё раз.",
    cancelError: "Не удалось остановить проверку. Попробуйте ещё раз.",
    qrError: "Не удалось подготовить ссылку. Попробуйте ещё раз.",
    lostConnection: "Соединение потеряно. Попробуйте ещё раз.",
    profileDetails: "ПОДРОБНЫЙ ПРОФИЛЬ",
    cityAndRegion: "Город и регион",
    professionalRole: "Профессиональная роль",
    household: "Домашняя ситуация",
    everydayHabits: "Повседневные привычки",
    decisionStyle: "Как принимает решения",
    digitalFamiliarity: "Знакомство с цифровыми сферами",
    confidently: "Уверенно",
    familiar: "Знакомо",
    beginner: "Начальный опыт",
    choiceStyle: "Стиль выбора",
    outOfFive: "из 5",
    profile: "Профиль аудитории",
    languageLabel: "Язык интерфейса",
    runCreated: "Запуск готов",
    toSources: "К источникам",
    startScenario: "Запустить сценарий",
    continueWithoutSources: "Продолжить без источников",
    toAudience: "К аудитории",
    prepareResearch: "Готовим исследование",
    launchResearch: "Запустить исследование",
    collectingResponses: "Собираем ответы",
    toResponseMap: "К карте реакций",
    toInsights: "К выводам",
    openResult: "Открыть результат",
    createQr: "Создать QR-код",
    back: "Назад",
    reportIdea: "Идея и результаты прогона",
    disclaimer: "Отчёт и аналитика созданы с помощью искусственного интеллекта, носят информационный характер и не являются инвестиционной рекомендацией или призывом к действию.",
  },
  en: {
    topNote: "Audience simulation",
    heroLineOne: "How will people",
    heroLineTwo: "respond to",
    heroLineThree: "your idea?",
    heroLead: "See who your idea could help—and what matters to them.",
    languageButton: "Русский",
    languageButtonLabel: "Switch the stand to Russian",
    beginLabel: "Start the idea check",
    ideaEyebrow: "01 / Choose an idea",
    ideaTitle: "What are we testing?",
    sourceEyebrow: "02 / Market signals",
    sourceTitleOne: "First, listen to",
    sourceTitleTwo: "the market",
    sourceLead: "See who is already talking about this problem and what they say.",
    sourcesFound: "sources found",
    scenarioSources: "sources in this scenario",
    bundleLinks: "links in the research bundle",
    pagesOpened: "pages opened",
    linkedSignals: "source-backed findings · scenario",
    signalsConfirmed: "signals linked to sources",
    reviews: "Customer reviews",
    reviewsScenario: "scenario sources",
    reviewsFound: "pages found",
    communities: "Professional communities",
    searchMaterials: "Search results",
    recurringSignals: "Recurring signals",
    linkedToSources: "linked to sources",
    linkedFindings: "scenario findings",
    sourceList: "Sources and page status",
    pageOpened: "page opened",
    addressBlocked: "address blocked",
    sourceReference: "research reference",
    notChecked: "not checked",
    verifiedQuotes: "Source-backed quotes",
    searchNotFound: "No sources found",
    searchReady: "Sources reviewed",
    searchStopped: "Search stopped",
    checkingQuotes: "checking quotes",
    linkingSignals: "Connecting findings to sources and recurring themes",
    connectingSearch: "Connecting to search sources",
    fallbackText: "Sonar could not find verifiable links. You can continue without source links or choose another ready-made idea.",
    chooseAnotherScenario: "Choose another idea",
    retrySourceProcessing: "Retry source processing",
    retryPreparation: "Retry setup",
    restart: "Start over",
    demoSourceFoot: "The counters show the scale of this demo scenario; the links below come from its research bundle.",
    sourceFoot: "Connecting mentions to their sources and recurring themes.",
    audienceEyebrow: "03 / Meet the audience",
    audienceTitleOne: "The people",
    audienceTitleTwo: "behind the idea",
    audienceLead: "Building an audience sample from the idea and market signals.",
    buildingProfiles: "Building profiles",
    selected: "selected",
    age: "Age",
    city: "City",
    occupation: "Occupation",
    income: "Income",
    habits: "Profile traits",
    personaAria: "Open the full profile",
    matchingAudience: "Matching the audience to market signals…",
    clickForProfile: "Select a card to see the full profile.",
    configureAudience: "Adjust audience groups",
    audienceComposition: "Audience composition",
    done: "Done",
    minimumProfiles: "Keep at least five profiles in the audience.",
    readyScenarioNote: "Ready-made scenario · {count} profiles · selected from a catalog of 1,500 profiles",
    panelSize: "Panel size",
    people: "people",
    constraints: "Constraints",
    optional: "Optional",
    interviewEyebrow: "05 / Simulated research",
    interviewTitleOne: "Collecting",
    interviewTitleTwo: "audience reactions",
    startingResearch: "Starting the research",
    respondingInGroups: "Personas are responding",
    connectingPersonas: "Connecting personas",
    mapEyebrow: "06 / Response map",
    mapTitleOne: "Audience",
    mapTitleTwo: "responses",
    problemAxis: "PROBLEM RELEVANCE",
    tryAxis: "WILLINGNESS TO TRY →",
    excluded: "EXCLUDED",
    excludedShort: "excluded",
    included: "included",
    problem: "Problem",
    interest: "Interest",
    tryIt: "Try it",
    noShortAnswer: "No short response",
    accounted: "Included",
    excludedCount: "excluded",
    answers: "responses",
    insightsEyebrow: "07 / Key takeaways",
    insightsTitleOne: "What the",
    insightsTitleTwo: "audience says",
    problemThreshold: "rated the problem’s relevance 7/10 or higher",
    businessMismatch: "Business profiles are selected, while this idea is aimed at consumers.",
    interestSeven: "interest · rating 7+",
    trySeven: "willing to try · rating 7+",
    responseCount: "Responses collected: {count}",
    resultReady: "Your result is ready",
    continueStudying: "Keep exploring",
    yourIdea: "the idea",
    scanQr: "Scan the code to open the full report and save your results.",
    openOnPhone: "Open the result<br />on your phone",
    qrAlt: "Report QR code",
    createQrPrompt: "Create a QR code to open and save the full report.",
    newRun: "New check",
    stages: "Check stages",
    loadingCampaign: "Loading the campaign",
    closeError: "Dismiss message",
    genericError: "Something went wrong. Please try again.",
    unavailableCampaign: "This campaign is currently unavailable.",
    openReadyScenarioError: "Could not open this idea. Please try again.",
    audienceChanged: "The audience has changed. Review it and start the research again.",
    audienceUpdated: "The audience has changed. Check the selected groups and start the research again.",
    confirmAudienceError: "Could not confirm the audience. Please try again.",
    continueError: "Could not continue the run. Please try again.",
    retryError: "Could not retry setup. Please try again.",
    cancelError: "Could not stop the check. Please try again.",
    qrError: "Could not create the report link. Please try again.",
    lostConnection: "Connection lost. Please try again.",
    profileDetails: "FULL PROFILE",
    cityAndRegion: "City and region",
    professionalRole: "Professional role",
    household: "Household",
    everydayHabits: "Profile tendencies",
    decisionStyle: "Decision-making style",
    digitalFamiliarity: "Digital familiarity",
    confidently: "Confident",
    familiar: "Some experience",
    beginner: "Beginner",
    choiceStyle: "Decision style",
    outOfFive: "out of 5",
    profile: "Audience profile",
    languageLabel: "Language",
    runCreated: "Run ready",
    toSources: "View market signals",
    startScenario: "Start this idea",
    continueWithoutSources: "Continue without source links",
    toAudience: "Meet the audience",
    prepareResearch: "Preparing the research",
    launchResearch: "Start the research",
    collectingResponses: "Collecting responses",
    toResponseMap: "View response map",
    toInsights: "View key takeaways",
    openResult: "Open the result",
    createQr: "Create QR code",
    back: "Back",
    reportIdea: "Idea and run results",
    disclaimer: "This report and analysis were created with artificial intelligence for informational purposes only. They are not investment advice or a call to action.",
  },
} as const;

export const scenarioCardsEn: Record<string, { title: string; note: string }> = {
  "calorie-photo": {
    title: "AI Photo Calorie Tracker",
    note: "Estimate ingredients, portion size, and calories from a meal photo; correct the result and keep a food diary.",
  },
  "english-coach": {
    title: "AI English Conversation Coach",
    note: "Practise short voice conversations for work, study, and travel, with feedback tailored to your level.",
  },
  "family-budget": {
    title: "Personal Budget Assistant",
    note: "Plan income and regular bills, see what remains until payday, and make a practical spending plan.",
  },
  "weekend-trip": {
    title: "Weekend Trip Planner",
    note: "Plan a weekend itinerary around your budget, interests, travel time, and group.",
  },
};

export const groupLabelsEn: Record<string, string> = {
  "Активный специалист старшего возраста": "Active older professional",
  "Взрослый учащийся или человек, меняющий профессию": "Adult learner or career changer",
  "Владелец малого розничного бизнеса": "Small retail business owner",
  "Житель небольшого города с практичным подходом": "Practical resident of a smaller city",
  "ИТ-руководитель с ответственностью за безопасность": "IT manager responsible for security",
  "Менеджер продукта в технологической компании": "Product manager at a technology company",
  "Молодой специалист с плотным графиком": "Busy young professional",
  "Операционный руководитель среднего бизнеса": "Operations lead at a mid-sized business",
  "Опытный специалист, тщательно сравнивающий варианты": "Experienced professional who compares options carefully",
  "Пенсионер, уверенно решающий знакомые задачи онлайн": "Retiree comfortable with familiar online tasks",
  "Работник с физической или сменной занятостью": "Shift or manual worker",
  "Родитель маленького ребёнка": "Parent of a young child",
  "Руководитель отдела персонала": "HR manager",
  "Самозанятый или независимый специалист": "Self-employed or independent professional",
  "Самозанятый предприниматель": "Self-employed business owner",
  "Специалист по закупкам крупной организации": "Procurement specialist at a large organization",
  "Студент, совмещающий учёбу и подработку": "Student balancing studies and part-time work",
  "Финансовый руководитель малого или среднего бизнеса": "Finance lead at a small or mid-sized business",
  "Цифровой специалист на удалённой работе": "Remote digital professional",
  "Человек, планирующий семейные расходы": "Person managing household expenses",
};

export const personaValueLabelsEn: Record<string, Record<string, string>> = {
  city: {
    "Владивосток": "Vladivostok", "Воронеж": "Voronezh", "Екатеринбург": "Yekaterinburg",
    "Иркутск": "Irkutsk", "Казань": "Kazan", "Краснодар": "Krasnodar",
    "Нижний Новгород": "Nizhny Novgorod", "Новосибирск": "Novosibirsk", "Пермь": "Perm",
    "Самара": "Samara", "Санкт-Петербург": "Saint Petersburg", "Тула": "Tula",
    "Тюмень": "Tyumen", "Уфа": "Ufa", "Ярославль": "Yaroslavl",
  },
  region: {
    "Дальневосточный федеральный округ": "Far Eastern Federal District",
    "Приволжский федеральный округ": "Volga Federal District",
    "Северо-Западный федеральный округ": "Northwestern Federal District",
    "Сибирский федеральный округ": "Siberian Federal District",
    "Уральский федеральный округ": "Ural Federal District",
    "Центральный федеральный округ": "Central Federal District",
    "Южный федеральный округ": "Southern Federal District",
  },
  citySize: { "крупный город": "Large city", "средний город": "Mid-sized city" },
  occupation: {
    "администратор, бухгалтер или офисный специалист": "Administrator, accountant, or office professional",
    "владелец магазина или точки услуг": "Shop or local-service business owner",
    "владелец микробизнеса": "Microbusiness owner",
    "инженер или технический специалист": "Engineer or technical specialist",
    "опытный специалист или руководитель": "Experienced professional or manager",
    "менеджер продукта или аналитик": "Product manager or analyst",
    "работник производства или сферы обслуживания": "Manufacturing or service worker",
    "работник, проходящий дополнительное обучение": "Worker taking additional training",
    "пенсионер, ранее работал в сфере образования или управления": "Retired; formerly worked in education or management",
    "руководитель ИТ или специалист по безопасности": "IT manager or security specialist",
    "руководитель операционного направления": "Operations manager",
    "руководитель отдела кадров или персонала": "HR manager",
    "самозанятый специалист": "Self-employed professional",
    "специалист или руководитель закупок": "Procurement specialist or manager",
    "специалист или руководитель среднего звена": "Mid-level specialist or manager",
    "специалист клиентского сервиса": "Customer support specialist",
    "специалист местной организации или малого бизнеса": "Local organization or small-business professional",
    "специалист по информационным технологиям": "IT professional",
    "студент, частичная занятость": "Student with part-time work",
    "финансовый директор или главный бухгалтер": "Finance director or chief accountant",
  },
  income: {
    "до 50 тыс. ₽/мес.": "Under RUB 50,000/month",
    "50-100 тыс. ₽/мес.": "RUB 50,000–100,000/month",
    "100-180 тыс. ₽/мес.": "RUB 100,000–180,000/month",
    "50-180 тыс. ₽/мес.": "RUB 50,000–180,000/month",
    "50-180 тыс. ₽/мес./мес., переменный": "RUB 50,000–180,000/month, variable",
    "50-180 тыс. ₽/мес., переменный": "RUB 50,000–180,000/month, variable",
    "до 100 тыс. ₽/мес.": "Up to RUB 100,000/month",
  },
  household: {
    "живёт один или с партнёром": "Lives alone or with a partner",
    "живёт один или с семьёй": "Lives alone or with family",
    "живёт один или с соседями": "Lives alone or with roommates",
    "живёт один, с партнёром или семьёй": "Lives alone, with a partner, or with family",
    "живёт с партнёром или семьёй": "Lives with a partner or family",
    "один или с партнёром": "Alone or with a partner",
    "один или с семьёй": "Alone or with family",
    "один, с партнёром или родственниками": "Alone, with a partner, or with relatives",
    "семья или совместное хозяйство": "Family or shared household",
    "семья с ребёнком дошкольного возраста": "Family with a preschool-age child",
  },
};

export const behaviorLabelsEn: Record<string, string> = {
  price_sensitivity: "Price sensitivity",
  digital_skill: "Digital confidence",
  trust_in_new_services: "Trust in unfamiliar services",
  readiness_to_try: "Openness to trying new products",
  complexity_tolerance: "Comfort with complexity",
  information_search_intensity: "How carefully they compare options",
};

export const domainLabelsEn: Record<string, string> = {
  ecommerce: "Online shopping",
  education: "Education",
  food_delivery: "Food delivery",
  finance: "Finance",
  travel: "Travel",
};

export const exclusionLabelsEn: Record<string, string> = {
  missing_required_score: "A required score is missing",
  invalid_score: "The score is not a whole number between 0 and 10",
  response_generation_failed: "The response could not be generated",
  response_not_received: "No response was received",
  persona_mismatch: "The response did not match the selected profile",
  unsupported_assumption_language: "The response included an unsupported assumption",
};
