"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { CheckCircle2, Loader2, Send } from "lucide-react";

import { describeApiError, getJson, postJson } from "@/lib/api";

type Field = { key: string; label?: string; description?: string; placeholder?: string; type?: "text" | "email" | "number" | "textarea" | "select"; required?: boolean; application_types?: Array<"project" | "participant">; options?: Array<string | { value: string; label: string }> };
type Revision = { applicant_name?: string | null; applicant_email?: string | null; application_type: "project" | "participant"; form_payload: Record<string, string>; review_comment?: string | null; revision_expires_at: string; form_schema: { title?: string; fields?: Field[]; required?: string[] }; cohort: { name: string }; accelerator: { name: string } };

export default function ApplicationRevisionPage() {
  const { token } = useParams<{ token: string }>(); const [revision, setRevision] = useState<Revision | null>(null); const [values, setValues] = useState<Record<string, string>>({}); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [submitted, setSubmitted] = useState(false); const [error, setError] = useState("");
  useEffect(() => { getJson<Revision>(`/api/accelerators/public/application-revisions/${encodeURIComponent(token)}`).then((row) => { setRevision(row); setValues(row.form_payload || {}); }).catch((reason) => setError(describeApiError(reason, "Ссылка недействительна или устарела"))).finally(() => setLoading(false)); }, [token]);
  const fields = useMemo(() => (revision?.form_schema.fields || []).filter((field) => !field.application_types?.length || field.application_types.includes(revision?.application_type || "project")), [revision]); const required = useMemo(() => new Set([...(revision?.form_schema.required || []).filter((key) => fields.some((field) => field.key === key)), ...fields.filter((field) => field.required).map((field) => field.key)]), [fields, revision]);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSubmitting(true); setError(""); try { await postJson(`/api/accelerators/public/application-revisions/${encodeURIComponent(token)}`, { form_payload: values }); setSubmitted(true); } catch (reason) { setError(describeApiError(reason, "Не удалось отправить исправленную заявку")); } finally { setSubmitting(false); } };
  if (loading) return <main className="min-h-[100dvh] grid place-items-center bg-black text-white"><Loader2 className="animate-spin text-white/50" /></main>;
  if (!revision) return <Shell><h1 className="text-3xl">Форма недоступна</h1><p className="mt-4 text-white/50">{error}</p></Shell>;
  if (submitted) return <Shell><CheckCircle2 className="mx-auto mb-6 h-12 w-12 text-emerald-400" /><h1 className="text-3xl sm:text-5xl">Исправления отправлены</h1><p className="my-5 text-white/50">Заявка снова передана организатору на рассмотрение.</p><Link href="/" className="text-white underline">На главную</Link></Shell>;
  return <main className="min-h-[100dvh] bg-black px-4 py-10 text-white"><div className="mx-auto max-w-3xl"><p className="text-xs uppercase tracking-[.2em] text-white/35">{revision.accelerator.name} · {revision.cohort.name}</p><h1 className="mt-3 text-4xl sm:text-6xl">Доработка заявки</h1><div className="mt-6 rounded-2xl border border-amber-300/15 bg-amber-300/[0.05] p-5"><p className="text-xs uppercase tracking-[.15em] text-amber-200/60">Комментарий организатора</p><p className="mt-2 whitespace-pre-wrap text-white/65">{revision.review_comment}</p></div><p className="mt-4 text-sm text-white/35">Ссылка действует до {new Date(revision.revision_expires_at).toLocaleString("ru-RU")}.</p><form onSubmit={submit} className="mt-8 space-y-5 rounded-3xl border border-white/10 bg-white/[0.025] p-5 sm:p-8"><div className="grid gap-4 sm:grid-cols-2"><ReadOnly label="Кандидат" value={revision.applicant_name || "—"} /><ReadOnly label="Email" value={revision.applicant_email || "—"} /></div>{fields.map((field) => <label key={field.key} className="block"><span className="mb-2 block text-sm text-white/70">{field.label || field.key}{required.has(field.key) && <span className="text-red-300"> *</span>}</span>{field.type === "textarea" ? <textarea rows={5} value={values[field.key] || ""} onChange={(event) => setValues({ ...values, [field.key]: event.target.value })} required={required.has(field.key)} className="revision-input resize-y" /> : field.type === "select" ? <select value={values[field.key] || ""} onChange={(event) => setValues({ ...values, [field.key]: event.target.value })} required={required.has(field.key)} className="revision-input"><option value="">Выберите вариант</option>{(field.options || []).map((option) => { const item = typeof option === "string" ? { value: option, label: option } : option; return <option key={item.value} value={item.value}>{item.label}</option>; })}</select> : <input type={field.type === "number" ? "number" : field.type === "email" ? "email" : "text"} value={values[field.key] || ""} onChange={(event) => setValues({ ...values, [field.key]: event.target.value })} required={required.has(field.key)} className="revision-input" />}{field.description && <span className="mt-2 block text-xs text-white/35">{field.description}</span>}</label>)}{error && <p role="alert" className="rounded-2xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-200">{error}</p>}<button disabled={submitting} className="flex w-full items-center justify-center gap-2 rounded-full bg-white px-6 py-4 font-semibold text-black disabled:opacity-50">{submitting ? <Loader2 size={17} className="animate-spin" /> : <Send size={17} />} Отправить исправления</button></form></div><style jsx global>{`.revision-input{width:100%;border-radius:1rem;border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.04);padding:.85rem 1rem;color:white;outline:none}.revision-input option{color:black}`}</style></main>;
}
function ReadOnly({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-white/35">{label}</p><p className="mt-1 text-sm text-white/65">{value}</p></div>; }
function Shell({ children }: { children: React.ReactNode }) { return <main className="min-h-[100dvh] grid place-items-center bg-black px-5 text-white"><section className="max-w-xl rounded-3xl border border-white/10 bg-white/[0.03] p-8 text-center sm:p-12">{children}</section></main>; }
