"""Add feedback to chat_messages

Revision ID: 6a19bbd91746
Revises: d126ebef2049
Create Date: 2026-03-02 19:43:36.170691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a19bbd91746'
down_revision = 'd126ebef2049'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promocodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('current_uses', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promocodes'))
    )
    with op.batch_alter_table('promocodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promocodes_code'), ['code'], unique=True)

    op.create_table('rag_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('chunks_added', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_logs'))
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('yookassa_payment_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('is_annual', sa.Boolean(), nullable=False),
    sa.Column('promo_code_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promocodes.id'], name=op.f('fk_payments_promo_code_id_promocodes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_yookassa_payment_id'), ['yookassa_payment_id'], unique=True)

    op.create_table('social_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_social_accounts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_accounts'))
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_chat_sessions_analysis_id_analyses'), 'analyses', ['analysis_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_tier', sa.String(length=50), server_default='free', nullable=False))
        batch_op.add_column(sa.Column('subscription_expires_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('subscription_expires_at')
        batch_op.drop_column('subscription_tier')

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_chat_sessions_analysis_id_analyses'), type_='foreignkey')
        batch_op.drop_column('analysis_id')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('feedback')

    op.drop_table('social_accounts')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_yookassa_payment_id'))

    op.drop_table('payments')
    op.drop_table('rag_logs')
    with op.batch_alter_table('promocodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promocodes_code'))

    op.drop_table('promocodes')
    # ### end Alembic commands ###
