"""Add social accounts

Revision ID: 9c0f2d889e6b
Revises: 0001
Create Date: 2026-02-17 06:16:49.231681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0f2d889e6b'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Define users table for offline mode
    users = sa.Table(
        'users',
        sa.MetaData(),
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text("0")),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text("1")),
        sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.text("0")),
        sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column('locked_until', sa.DateTime(), nullable=True),
        sa.Column('email_verify_token_hash', sa.String(length=255), nullable=True),
        sa.Column("email_verify_expires_at", sa.DateTime(), nullable=True),
        sa.Column("password_reset_token_hash", sa.String(length=255), nullable=True),
        sa.Column("password_reset_expires_at", sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
    )

    with op.batch_alter_table('users', schema=None, copy_from=users) as batch_op:
        batch_op.alter_column('password_hash',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Define users table for offline mode
    users = sa.Table(
        'users',
        sa.MetaData(),
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=True), # Note: nullable=True here as we are reversing from that state
        sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text("0")),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text("1")),
        sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.text("0")),
        sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column('locked_until', sa.DateTime(), nullable=True),
        sa.Column('email_verify_token_hash', sa.String(length=255), nullable=True),
        sa.Column("email_verify_expires_at", sa.DateTime(), nullable=True),
        sa.Column("password_reset_token_hash", sa.String(length=255), nullable=True),
        sa.Column("password_reset_expires_at", sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
    )
    
    with op.batch_alter_table('users', schema=None, copy_from=users) as batch_op:
        batch_op.alter_column('password_hash',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=False)
    op.drop_table('social_accounts')
    # ### end Alembic commands ###
