"""Add PromoCode and Lockbox support

Revision ID: db92e39bd99e
Revises: 3e5e912aee5f
Create Date: 2026-02-23 02:48:52.326813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db92e39bd99e'
down_revision = '3e5e912aee5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promocodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('current_uses', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promocodes'))
    )
    with op.batch_alter_table('promocodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promocodes_code'), ['code'], unique=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promo_code_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_payments_promo_code_id_promocodes'), 'promocodes', ['promo_code_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payments_promo_code_id_promocodes'), type_='foreignkey')
        batch_op.drop_column('promo_code_id')

    with op.batch_alter_table('promocodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promocodes_code'))

    op.drop_table('promocodes')
    # ### end Alembic commands ###
