"""add cookie_consent

Revision ID: de426ffb6999
Revises: 6a19bbd91746
Create Date: 2026-03-10 19:19:19.523258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de426ffb6999'
down_revision = '6a19bbd91746'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cookie_consent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cookie_consent')

    # ### end Alembic commands ###
