"""Add sources column to messages

Revision ID: e2a9b4c7d6e8
Revises: fc256ba6b137
Create Date: 2026-04-06 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a9b4c7d6e8'
down_revision = 'fc256ba6b137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('sources', sa.JSON(), nullable=True))
    op.add_column('tree_chat_history', sa.Column('sources', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tree_chat_history', 'sources')
    op.drop_column('chat_messages', 'sources')
    # ### end Alembic commands ###
