"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowUpRight, FileSearch, Loader2, RefreshCw, Search, X } from "lucide-react";
import { describeApiError, getAuthJson } from "@/lib/api";

type ArtifactStatus = "started" | "ready" | "failed";
type ActionType = "chat" | "roadmap" | "research" | "custdev" | "grants" | "presentation";
type Artifact = { id:number; artifact_type:ActionType; status:ArtifactStatus; title:string; summary?:string|null; url?:string|null; updated_at?:string|null; details_visible:boolean; resident:{id:number;name:string}; project:{id:number;name:string}; action:{id:number;title:string;action_type:ActionType}; stage:{id:number;title:string} };
type Response = { access_role:"global_admin"|"organizer"|"tracker"; artifacts:Artifact[] };
const statusLabel={started:"В работе",ready:"Готово",failed:"Ошибка"} as const;
const statusClass={started:"text-amber-200 border-amber-300/25",ready:"text-emerald-300 border-emerald-300/25",failed:"text-red-200 border-red-300/25"} as const;
const typeLabel:Record<ActionType,string>={chat:"Чат",roadmap:"Дорожная карта",research:"Исследование",custdev:"CustDev",grants:"Гранты",presentation:"Презентация"};

export function ArtifactWorkspace({cohortId,token}:{cohortId:number;token:string}){
  const [data,setData]=useState<Response|null>(null); const [query,setQuery]=useState(""); const [filter,setFilter]=useState<"all"|ArtifactStatus|"shared">("all"); const [selected,setSelected]=useState<Artifact|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{setData(await getAuthJson<Response>(`/api/accelerators/cohorts/${cohortId}/artifacts`,token));}catch(reason){setError(describeApiError(reason,"Не удалось загрузить результаты Pitchy"));}finally{setLoading(false);}},[cohortId,token]);
  useEffect(()=>{void load();},[load]); useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setSelected(null)};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[]);
  const rows=useMemo(()=>{const needle=query.trim().toLowerCase();return(data?.artifacts||[]).filter(row=>(filter==="all"||(filter==="shared"?row.details_visible:row.status===filter))&&(!needle||[row.resident.name,row.project.name,row.stage.title,row.action.title].some(value=>value.toLowerCase().includes(needle))));},[data,filter,query]);
  const counts=useMemo(()=>({all:data?.artifacts.length||0,ready:data?.artifacts.filter(r=>r.status==="ready").length||0,started:data?.artifacts.filter(r=>r.status==="started").length||0,failed:data?.artifacts.filter(r=>r.status==="failed").length||0,shared:data?.artifacts.filter(r=>r.details_visible).length||0}),[data]);
  return <section>
    <header className="flex flex-wrap items-end justify-between gap-4 border-b border-white/8 pb-6"><div><p className="text-xs text-white/35">Обзор потока&nbsp; / &nbsp;Результаты</p><h1 className="mt-3 text-3xl font-semibold">Результаты Pitchy</h1><p className="mt-2 text-sm text-white/45">{counts.all} запущено · {counts.ready} готово · {counts.shared} открыто вам</p></div><button type="button" onClick={()=>void load()} className="overview-secondary" disabled={loading}><RefreshCw size={15} className={loading?"animate-spin":""}/>Обновить</button></header>
    <p className="mt-5 rounded-xl border border-white/8 px-4 py-3 text-sm text-white/45">Здесь отображаются только опубликованные резидентами описания. Полные рабочие данные остаются в их личном пространстве.</p>
    <div className="mt-5"><label className="relative block"><Search size={16} className="absolute left-4 top-1/2 -translate-y-1/2 text-white/30"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Резидент, проект, этап или результат" className="workspace-input !pl-11"/></label></div>
    <div className="mt-4 flex gap-2 overflow-x-auto">{([['all','Все'],['ready','Готово'],['started','В работе'],['failed','Ошибка'],['shared','Доступно мне']] as const).map(([key,label])=><button key={key} type="button" onClick={()=>setFilter(key)} className={`shrink-0 rounded-xl border px-3 py-2 text-sm ${filter===key?'border-white bg-white text-black':'border-white/10 text-white/50'}`}>{label}<span className="ml-2 opacity-60">{counts[key]}</span></button>)}</div>
    {error&&<p role="alert" className="mt-5 rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-red-200">{error}</p>}
    {loading&&!data?<div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-white/35"/></div>:<div className="mt-5 overflow-hidden rounded-2xl border border-white/9"><div className="hidden grid-cols-[1.15fr_1.2fr_1fr_120px_140px_135px] gap-4 border-b border-white/8 bg-white/[.025] px-4 py-3 text-xs text-white/35 lg:grid"><span>Резидент / проект</span><span>Результат</span><span>Этап</span><span>Статус</span><span>Доступ</span><span>Обновлено</span></div>{rows.map(row=><button key={row.id} type="button" onClick={()=>row.details_visible&&setSelected(row)} disabled={!row.details_visible} className="grid w-full gap-3 border-b border-white/8 p-4 text-left last:border-0 disabled:cursor-default lg:grid-cols-[1.15fr_1.2fr_1fr_120px_140px_135px] lg:items-center"><span><b className="block text-sm font-medium">{row.resident.name}</b><small className="text-white/40">{row.project.name}</small></span><span><b className="block text-sm font-medium">{row.action.title}</b><small className="text-white/40">{typeLabel[row.action.action_type]}</small></span><span className="text-sm text-white/55">{row.stage.title}</span><span className={`w-fit rounded-full border px-2.5 py-1 text-xs ${statusClass[row.status]}`}>{statusLabel[row.status]}</span><span className={`text-sm ${row.details_visible?'text-emerald-300':'text-white/35'}`}>{row.details_visible?'Доступ открыт':'Не опубликовано'}</span><span className="text-xs text-white/40">{row.updated_at?new Date(row.updated_at).toLocaleString('ru-RU'):'—'}</span></button>)}{!rows.length&&<div className="py-16 text-center"><FileSearch className="mx-auto text-white/20"/><p className="mt-3">Результаты не найдены</p></div>}</div>}
    {selected&&<div className="fixed inset-0 z-[80] flex justify-end bg-black/70" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><aside role="dialog" aria-modal="true" aria-labelledby="artifact-title" className="h-full w-full max-w-xl overflow-y-auto border-l border-white/10 bg-[#1c1b1b] p-6"><div className="flex justify-between gap-4"><div><p className="text-xs text-white/35">{selected.resident.name} · {selected.project.name}</p><h2 id="artifact-title" className="mt-2 text-2xl">{selected.title||selected.action.title}</h2></div><button onClick={()=>setSelected(null)} aria-label="Закрыть"><X/></button></div><p className="mt-3 text-sm text-white/45">{selected.stage.title} · {typeLabel[selected.action.action_type]}</p>{selected.summary?<p className="mt-6 whitespace-pre-wrap leading-7 text-white/70">{selected.summary}</p>:<p className="mt-6 text-white/40">Опубликованное описание не заполнено.</p>}{selected.url&&<a href={selected.url} target="_blank" rel="noreferrer" className="workspace-button mt-6">Открыть результат <ArrowUpRight size={15}/></a>}</aside></div>}
  </section>;
}
