"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import Image from "next/image";
import { Archive, CalendarDays, Check, Clipboard, Copy, ExternalLink, History, Loader2, MapPin, Pencil, Plus, QrCode, Send, Users, X } from "lucide-react";

import { describeApiError, getAuthJson, patchAuthJson, postAuthJson, putAuthJson } from "@/lib/api";

type HomeworkLink = { assignment_id: number; relation: "before" | "during" | "after"; title?: string };
type MaterialLink = { title: string; url: string };
type EventStatus = "draft" | "published" | "completed" | "cancelled";
type EventRow = {
  id: number; stage_id?: number | null; title: string; description?: string | null;
  event_type: "webinar" | "workshop" | "tracker_session" | "expert_session" | "networking" | "other";
  host_name?: string | null; starts_at: string; ends_at: string; event_format: "online" | "offline" | "hybrid";
  location?: string | null; meeting_url?: string | null; online_platform?: string | null; venue_details?: string | null;
  map_url?: string | null; recording_url?: string | null; outcome?: string | null; next_step?: string | null;
  post_materials: MaterialLink[]; cancellation_reason?: string | null; timezone?: string | null;
  homework_links: HomeworkLink[]; status: EventStatus; checkin_url: string; attendance_count: number;
};
type EventHistory = { id: number; action: string; reason?: string | null; created_at: string; actor?: { name: string } | null };
type Attendee = { membership_id: number; name: string; email: string; status: "not_marked" | "present" | "absent" | "excused" };
type Option = { id: number; title: string; status: string };
type RescheduleForm = { id: number; startsAt: string; endsAt: string; reason: string };
type FollowupForm = { id: number; recordingUrl: string; outcome: string; nextStep: string; materials: MaterialLink[] };

const localDate = (value: string) => { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16); };
const empty = { title: "", description: "", stageId: "", eventType: "webinar" as EventRow["event_type"], hostName: "", startsAt: "", endsAt: "", format: "online" as EventRow["event_format"], location: "", meetingUrl: "", onlinePlatform: "", venueDetails: "", mapUrl: "", homeworkLinks: [] as HomeworkLink[] };
const statusLabel: Record<EventStatus, string> = { draft: "Черновик", published: "Опубликовано", completed: "Завершено", cancelled: "Отменено" };
const actionLabel: Record<string, string> = { created: "Создано", updated: "Изменено", published: "Опубликовано", rescheduled: "Перенесено", cancelled: "Отменено", completed: "Завершено автоматически", followup_updated: "Добавлены итоги" };
const relationLabel = { before: "до", during: "во время", after: "после" } as const;

export function AttendanceManager({ cohortId, token }: { cohortId: number; token: string }) {
  const [events, setEvents] = useState<EventRow[]>([]);
  const [homework, setHomework] = useState<Option[]>([]);
  const [stages, setStages] = useState<Option[]>([]);
  const [form, setForm] = useState(empty);
  const [showForm, setShowForm] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [openId, setOpenId] = useState<number | null>(null);
  const [attendees, setAttendees] = useState<Record<number, Attendee[]>>({});
  const [history, setHistory] = useState<Record<number, EventHistory[]>>({});
  const [historyId, setHistoryId] = useState<number | null>(null);
  const [reschedule, setReschedule] = useState<RescheduleForm | null>(null);
  const [cancellation, setCancellation] = useState<{ id: number; reason: string } | null>(null);
  const [followup, setFollowup] = useState<FollowupForm | null>(null);
  const [busy, setBusy] = useState("");
  const [error, setError] = useState("");

  const load = useCallback(async () => {
    setError("");
    try {
      const [eventRows, homeworkRows, stageRows] = await Promise.all([
        getAuthJson<EventRow[]>(`/api/accelerators/cohorts/${cohortId}/events`, token),
        getAuthJson<Option[]>(`/api/accelerators/cohorts/${cohortId}/homework`, token).catch(() => []),
        getAuthJson<Option[]>(`/api/accelerators/cohorts/${cohortId}/program-stages`, token).catch(() => []),
      ]);
      setEvents(eventRows); setHomework(homeworkRows); setStages(stageRows);
    } catch (reason) { setError(describeApiError(reason, "Не удалось загрузить мероприятия")); }
  }, [cohortId, token]);
  useEffect(() => { void load(); }, [load]);

  const save = async (event: FormEvent) => {
    event.preventDefault(); setBusy("save"); setError("");
    const payload = { title: form.title, description: form.description || null, stage_id: form.stageId ? Number(form.stageId) : null, event_type: form.eventType, host_name: form.hostName || null, starts_at: new Date(form.startsAt).toISOString(), ends_at: new Date(form.endsAt).toISOString(), event_format: form.format, location: form.location || null, meeting_url: form.meetingUrl || null, online_platform: form.onlinePlatform || null, venue_details: form.venueDetails || null, map_url: form.mapUrl || null, homework_links: form.homeworkLinks };
    try { if (editingId) await putAuthJson(`/api/accelerators/events/${editingId}`, payload, token); else await postAuthJson(`/api/accelerators/cohorts/${cohortId}/events`, payload, token); setForm(empty); setEditingId(null); setShowForm(false); await load(); }
    catch (reason) { setError(describeApiError(reason, "Не удалось сохранить мероприятие")); } finally { setBusy(""); }
  };
  const publish = async (id: number) => { setBusy(`publish-${id}`); try { await postAuthJson(`/api/accelerators/events/${id}/publish`, {}, token); await load(); } catch (reason) { setError(describeApiError(reason, "Не удалось опубликовать мероприятие")); } finally { setBusy(""); } };
  const edit = (row: EventRow) => { setForm({ title: row.title, description: row.description || "", stageId: row.stage_id ? String(row.stage_id) : "", eventType: row.event_type, hostName: row.host_name || "", startsAt: localDate(row.starts_at), endsAt: localDate(row.ends_at), format: row.event_format, location: row.location || "", meetingUrl: row.meeting_url || "", onlinePlatform: row.online_platform || "", venueDetails: row.venue_details || "", mapUrl: row.map_url || "", homeworkLinks: row.homework_links || [] }); setEditingId(row.id); setShowForm(true); };
  const lifecycle = async (row: EventRow, action: "duplicate" | "archive") => { if (action === "archive" && !window.confirm(`Архивировать мероприятие «${row.title}»?`)) return; setBusy(`${action}-${row.id}`); try { await postAuthJson(`/api/accelerators/events/${row.id}/${action}`, {}, token); await load(); } catch (reason) { setError(describeApiError(reason, "Не удалось выполнить действие")); } finally { setBusy(""); } };
  const submitReschedule = async (event: FormEvent) => { event.preventDefault(); if (!reschedule) return; setBusy(`reschedule-${reschedule.id}`); try { await postAuthJson(`/api/accelerators/events/${reschedule.id}/reschedule`, { starts_at: new Date(reschedule.startsAt).toISOString(), ends_at: new Date(reschedule.endsAt).toISOString(), reason: reschedule.reason }, token); setReschedule(null); await load(); } catch (reason) { setError(describeApiError(reason, "Не удалось перенести мероприятие")); } finally { setBusy(""); } };
  const submitCancellation = async (event: FormEvent) => { event.preventDefault(); if (!cancellation) return; setBusy(`cancel-${cancellation.id}`); try { await postAuthJson(`/api/accelerators/events/${cancellation.id}/cancel`, { reason: cancellation.reason }, token); setCancellation(null); await load(); } catch (reason) { setError(describeApiError(reason, "Не удалось отменить мероприятие")); } finally { setBusy(""); } };
  const submitFollowup = async (event: FormEvent) => { event.preventDefault(); if (!followup) return; setBusy(`followup-${followup.id}`); try { await putAuthJson(`/api/accelerators/events/${followup.id}/followup`, { recording_url: followup.recordingUrl || null, outcome: followup.outcome || null, next_step: followup.nextStep || null, post_materials: followup.materials.filter((item) => item.title.trim() && item.url.trim()) }, token); setFollowup(null); await load(); } catch (reason) { setError(describeApiError(reason, "Не удалось сохранить итоги")); } finally { setBusy(""); } };
  const toggleHistory = async (id: number) => { if (historyId === id) { setHistoryId(null); return; } setHistoryId(id); if (!history[id]) try { const rows = await getAuthJson<EventHistory[]>(`/api/accelerators/events/${id}/history`, token); setHistory((current) => ({ ...current, [id]: rows })); } catch (reason) { setError(describeApiError(reason, "Не удалось загрузить историю")); } };
  const openAttendance = async (id: number) => { if (openId === id) { setOpenId(null); return; } setOpenId(id); try { const rows = await getAuthJson<Attendee[]>(`/api/accelerators/events/${id}/attendance`, token); setAttendees((current) => ({ ...current, [id]: rows })); } catch (reason) { setError(describeApiError(reason, "Не удалось загрузить посещаемость")); } };
  const mark = async (eventId: number, membershipId: number, status: "present" | "absent" | "excused") => { try { await patchAuthJson(`/api/accelerators/events/${eventId}/attendance`, { membership_id: membershipId, status }, token); const rows = await getAuthJson<Attendee[]>(`/api/accelerators/events/${eventId}/attendance`, token); setAttendees((current) => ({ ...current, [eventId]: rows })); await load(); } catch (reason) { setError(describeApiError(reason, "Не удалось сохранить посещаемость")); } };

  return <section className="workspace-card">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl">Мероприятия</h2><p className="mt-1 text-sm text-white/40">События входят в этапы программы. Перенос и отмена сохраняются в истории.</p></div><button type="button" onClick={() => { if (showForm) { setShowForm(false); setEditingId(null); setForm(empty); } else setShowForm(true); }} className="workspace-button"><Plus size={15} />{showForm ? "Закрыть" : "Новое мероприятие"}</button></div>
    {error && <p role="alert" className="mt-5 rounded-2xl border border-red-400/20 bg-red-400/10 px-4 py-3 text-sm text-red-200">{error}</p>}
    {showForm && <form onSubmit={save} className="mt-6 rounded-2xl border border-white/10 bg-black/25 p-4 sm:p-5"><h3 className="mb-4">{editingId ? "Редактирование черновика" : "Новое мероприятие"}</h3><div className="grid gap-4 sm:grid-cols-2">
      <label className="text-sm text-white/60 sm:col-span-2">Название<input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required minLength={2} className="workspace-input mt-2" /></label>
      <label className="text-sm text-white/60">Этап<select value={form.stageId} onChange={(e) => setForm({ ...form, stageId: e.target.value })} className="workspace-input mt-2"><option value="">Без этапа</option>{stages.map((stage) => <option key={stage.id} value={stage.id}>{stage.title}</option>)}</select></label>
      <label className="text-sm text-white/60">Тип<select value={form.eventType} onChange={(e) => setForm({ ...form, eventType: e.target.value as EventRow["event_type"] })} className="workspace-input mt-2"><option value="webinar">Вебинар</option><option value="workshop">Воркшоп</option><option value="tracker_session">Сессия с трекером</option><option value="expert_session">Сессия с экспертом</option><option value="networking">Нетворкинг</option><option value="other">Другое</option></select></label>
      <label className="text-sm text-white/60">Ведущий<input value={form.hostName} onChange={(e) => setForm({ ...form, hostName: e.target.value })} placeholder="Имя и роль" className="workspace-input mt-2" /></label><span />
      <label className="text-sm text-white/60">Начало<input type="datetime-local" value={form.startsAt} onChange={(e) => setForm({ ...form, startsAt: e.target.value })} required className="workspace-input mt-2" /></label><label className="text-sm text-white/60">Окончание<input type="datetime-local" value={form.endsAt} onChange={(e) => setForm({ ...form, endsAt: e.target.value })} required className="workspace-input mt-2" /></label>
      <label className="text-sm text-white/60">Формат<select value={form.format} onChange={(e) => setForm({ ...form, format: e.target.value as EventRow["event_format"] })} className="workspace-input mt-2"><option value="online">Онлайн</option><option value="offline">Очно</option><option value="hybrid">Гибрид</option></select></label>
      {form.format !== "online" && <label className="text-sm text-white/60">Адрес<input value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} required className="workspace-input mt-2" /></label>}
      {form.format !== "offline" && <><label className="text-sm text-white/60">Ссылка на подключение<input type="url" value={form.meetingUrl} onChange={(e) => setForm({ ...form, meetingUrl: e.target.value })} required className="workspace-input mt-2" /></label><label className="text-sm text-white/60">Платформа<input value={form.onlinePlatform} onChange={(e) => setForm({ ...form, onlinePlatform: e.target.value })} className="workspace-input mt-2" /></label></>}
      {form.format !== "online" && <><label className="text-sm text-white/60">Карта<input type="url" value={form.mapUrl} onChange={(e) => setForm({ ...form, mapUrl: e.target.value })} className="workspace-input mt-2" /></label><label className="text-sm text-white/60 sm:col-span-2">Как пройти<textarea value={form.venueDetails} onChange={(e) => setForm({ ...form, venueDetails: e.target.value })} rows={2} className="workspace-input mt-2 resize-y" /></label></>}
      <label className="text-sm text-white/60 sm:col-span-2">Описание<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} rows={3} className="workspace-input mt-2 resize-y" /></label>
    </div><HomeworkLinks homework={homework} links={form.homeworkLinks} onChange={(homeworkLinks) => setForm({ ...form, homeworkLinks })} /><div className="mt-5 flex justify-end"><button disabled={busy === "save"} className="workspace-button">{busy === "save" && <Loader2 size={15} className="animate-spin" />} Сохранить черновик</button></div></form>}
    <div className="mt-6 space-y-3">{!events.length ? <p className="py-6 text-center text-sm text-white/35">Мероприятий пока нет.</p> : events.map((row) => <article key={row.id} className="rounded-2xl border border-white/9 bg-white/[0.02] p-4 sm:p-5"><EventHeader row={row} onEdit={edit} onPublish={publish} onAttendance={openAttendance} onReschedule={() => setReschedule({ id: row.id, startsAt: localDate(row.starts_at), endsAt: localDate(row.ends_at), reason: "" })} onCancel={() => setCancellation({ id: row.id, reason: "" })} onFollowup={() => setFollowup({ id: row.id, recordingUrl: row.recording_url || "", outcome: row.outcome || "", nextStep: row.next_step || "", materials: row.post_materials || [] })} onHistory={toggleHistory} onLifecycle={lifecycle} />
      <EventDetails row={row} />
      {row.status === "published" && <details className="mt-4 rounded-2xl border border-white/8 p-4"><summary className="cursor-pointer text-sm text-white/55"><QrCode size={15} className="mr-2 inline" />QR-код для отметки</summary><div className="mt-4 flex flex-wrap items-center gap-5"><div className="rounded-2xl bg-white p-3"><Image unoptimized src={`/api/accelerators/events/${row.id}/qr`} alt={`QR-код для ${row.title}`} width={160} height={160} /></div><button type="button" onClick={() => void navigator.clipboard.writeText(row.checkin_url)} className="workspace-button !bg-transparent !text-white"><Clipboard size={14} /> Копировать ссылку</button></div></details>}
      {reschedule?.id === row.id && <ReschedulePanel value={reschedule} onChange={setReschedule} onSubmit={submitReschedule} onClose={() => setReschedule(null)} />}
      {cancellation?.id === row.id && <form onSubmit={submitCancellation} className="mt-4 rounded-2xl border border-red-300/15 bg-red-300/[0.03] p-4"><label className="text-xs text-white/50">Причина отмены<textarea required minLength={2} value={cancellation.reason} onChange={(e) => setCancellation({ ...cancellation, reason: e.target.value })} className="workspace-input mt-2" /></label><div className="mt-3 flex gap-2"><button className="workspace-button !bg-red-100">Отменить мероприятие</button><button type="button" onClick={() => setCancellation(null)} className="workspace-button !bg-transparent !text-white">Закрыть</button></div></form>}
      {followup?.id === row.id && <FollowupPanel value={followup} onChange={setFollowup} onSubmit={submitFollowup} onClose={() => setFollowup(null)} />}
      {historyId === row.id && <div className="mt-4 rounded-2xl border border-white/8 p-4"><h4 className="text-sm">История изменений</h4><div className="mt-3 space-y-2">{(history[row.id] || []).map((item) => <div key={item.id} className="rounded-xl bg-black/25 p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><span>{actionLabel[item.action] || item.action}</span><span className="text-xs text-white/30">{new Date(item.created_at).toLocaleString("ru-RU")}</span></div>{item.reason && <p className="mt-1 text-xs text-white/45">Причина: {item.reason}</p>}<p className="mt-1 text-xs text-white/30">{item.actor?.name || "Система"}</p></div>)}</div></div>}
      {openId === row.id && <AttendancePanel attendees={attendees[row.id] || []} eventId={row.id} onMark={mark} />}
    </article>)}</div>
  </section>;
}

function HomeworkLinks({ homework, links, onChange }: { homework: Option[]; links: HomeworkLink[]; onChange: (value: HomeworkLink[]) => void }) {
  if (!homework.length) return null;
  return <div className="mt-5 rounded-2xl border border-white/8 p-4"><p className="mb-3 text-sm text-white/55">Связанные домашние задания</p><div className="space-y-2">{homework.map((assignment) => { const link = links.find((row) => row.assignment_id === assignment.id); return <div key={assignment.id} className="flex flex-wrap items-center gap-3 rounded-xl bg-white/[0.025] p-3"><label className="flex min-w-0 flex-1 items-center gap-3 text-sm text-white/60"><input type="checkbox" checked={Boolean(link)} onChange={(e) => onChange(e.target.checked ? [...links, { assignment_id: assignment.id, relation: "after" }] : links.filter((row) => row.assignment_id !== assignment.id))} /><span className="truncate">{assignment.title}</span></label>{link && <select value={link.relation} onChange={(e) => onChange(links.map((row) => row.assignment_id === assignment.id ? { ...row, relation: e.target.value as HomeworkLink["relation"] } : row))} className="workspace-input !w-auto"><option value="before">До</option><option value="during">Во время</option><option value="after">После</option></select>}</div>; })}</div></div>;
}

function EventHeader({ row, onEdit, onPublish, onAttendance, onReschedule, onCancel, onFollowup, onHistory, onLifecycle }: { row: EventRow; onEdit: (row: EventRow) => void; onPublish: (id: number) => void; onAttendance: (id: number) => void; onReschedule: () => void; onCancel: () => void; onFollowup: () => void; onHistory: (id: number) => void; onLifecycle: (row: EventRow, action: "duplicate" | "archive") => void }) {
  return <div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0"><div className="mb-2 flex flex-wrap items-center gap-2"><span className={`rounded-full px-2 py-1 text-xs ${row.status === "completed" ? "bg-emerald-400/10 text-emerald-300" : row.status === "cancelled" ? "bg-red-400/10 text-red-200" : row.status === "published" ? "bg-blue-400/10 text-blue-200" : "bg-white/7 text-white/40"}`}>{statusLabel[row.status]}</span><span className="text-xs text-white/35"><Users size={12} className="mr-1 inline" />{row.attendance_count}</span></div><h3 className="text-lg">{row.title}</h3><p className="mt-2 text-sm text-white/45"><CalendarDays size={14} className="mr-1 inline" />{new Date(row.starts_at).toLocaleString("ru-RU", { timeZone: row.timezone || undefined })} — {new Date(row.ends_at).toLocaleTimeString("ru-RU", { hour: "2-digit", minute: "2-digit", timeZone: row.timezone || undefined })}{row.timezone ? ` · ${row.timezone}` : ""}</p>{row.host_name && <p className="mt-1 text-sm text-white/40">Ведущий: {row.host_name}</p>}{row.location && <p className="mt-1 text-sm text-white/40"><MapPin size={14} className="mr-1 inline" />{row.location}</p>}{row.cancellation_reason && <p className="mt-2 text-sm text-red-200">Причина: {row.cancellation_reason}</p>}</div><div className="flex flex-wrap gap-2">{row.status === "draft" ? <><button type="button" onClick={() => onEdit(row)} className="workspace-button !bg-transparent !text-white"><Pencil size={14} /> Изменить</button><button type="button" onClick={() => void onPublish(row.id)} className="workspace-button"><Send size={14} /> Опубликовать</button></> : row.status !== "cancelled" && <><button type="button" onClick={() => void onAttendance(row.id)} className="workspace-button"><Users size={14} /> Посещение</button>{row.status === "published" && <><button type="button" onClick={onReschedule} className="workspace-button !bg-transparent !text-white">Перенести</button><button type="button" onClick={onCancel} className="workspace-button !bg-transparent !text-red-200"><X size={14} /> Отменить</button></>}<button type="button" onClick={onFollowup} className="workspace-button !bg-transparent !text-white">Итоги</button></>}<button type="button" onClick={() => void onHistory(row.id)} className="rounded-full border border-white/10 p-2 text-white/50" aria-label="История изменений"><History size={15} /></button><button type="button" onClick={() => void onLifecycle(row, "duplicate")} className="rounded-full border border-white/10 p-2 text-white/50" aria-label="Создать копию"><Copy size={15} /></button><button type="button" onClick={() => void onLifecycle(row, "archive")} className="rounded-full border border-white/10 p-2 text-white/50" aria-label="Архивировать"><Archive size={15} /></button></div></div>;
}

function EventDetails({ row }: { row: EventRow }) {
  return <>{!!row.homework_links.length && <div className="mt-4 flex flex-wrap gap-2">{row.homework_links.map((link) => <span key={link.assignment_id} className="rounded-full border border-white/8 px-3 py-1.5 text-xs text-white/45">ДЗ {relationLabel[link.relation]}: {link.title || `#${link.assignment_id}`}</span>)}</div>}{row.recording_url && <a href={row.recording_url} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-1 text-sm text-blue-300 underline">Запись <ExternalLink size={13} /></a>}{row.outcome && <p className="mt-3 whitespace-pre-wrap text-sm text-white/55"><span className="text-white/35">Итог:</span> {row.outcome}</p>}{row.next_step && <p className="mt-2 text-sm text-white/55"><span className="text-white/35">Следующий шаг:</span> {row.next_step}</p>}{!!row.post_materials.length && <div className="mt-3 flex flex-wrap gap-2">{row.post_materials.map((item) => <a key={item.url} href={item.url} target="_blank" rel="noreferrer" className="rounded-full border border-white/10 px-3 py-1.5 text-xs text-blue-200">{item.title}</a>)}</div>}</>;
}

function ReschedulePanel({ value, onChange, onSubmit, onClose }: { value: RescheduleForm; onChange: (value: RescheduleForm) => void; onSubmit: (event: FormEvent) => void; onClose: () => void }) {
  return <form onSubmit={onSubmit} className="mt-4 grid gap-3 rounded-2xl border border-blue-300/15 bg-blue-300/[0.03] p-4 sm:grid-cols-2"><label className="text-xs text-white/50">Новое начало<input type="datetime-local" required value={value.startsAt} onChange={(e) => onChange({ ...value, startsAt: e.target.value })} className="workspace-input mt-2" /></label><label className="text-xs text-white/50">Новое окончание<input type="datetime-local" required value={value.endsAt} onChange={(e) => onChange({ ...value, endsAt: e.target.value })} className="workspace-input mt-2" /></label><label className="text-xs text-white/50 sm:col-span-2">Причина<textarea required minLength={2} value={value.reason} onChange={(e) => onChange({ ...value, reason: e.target.value })} className="workspace-input mt-2" /></label><div className="flex gap-2 sm:col-span-2"><button className="workspace-button">Сохранить перенос</button><button type="button" onClick={onClose} className="workspace-button !bg-transparent !text-white">Закрыть</button></div></form>;
}

function FollowupPanel({ value, onChange, onSubmit, onClose }: { value: FollowupForm; onChange: (value: FollowupForm) => void; onSubmit: (event: FormEvent) => void; onClose: () => void }) {
  return <form onSubmit={onSubmit} className="mt-4 grid gap-3 rounded-2xl border border-white/8 p-4 sm:grid-cols-2"><label className="text-xs text-white/50 sm:col-span-2">Ссылка на запись<input type="url" value={value.recordingUrl} onChange={(e) => onChange({ ...value, recordingUrl: e.target.value })} className="workspace-input mt-2" /></label><label className="text-xs text-white/50">Итог<textarea rows={3} value={value.outcome} onChange={(e) => onChange({ ...value, outcome: e.target.value })} className="workspace-input mt-2" /></label><label className="text-xs text-white/50">Следующий шаг<textarea rows={3} value={value.nextStep} onChange={(e) => onChange({ ...value, nextStep: e.target.value })} className="workspace-input mt-2" /></label><div className="sm:col-span-2"><div className="mb-2 flex items-center justify-between"><p className="text-xs text-white/50">Материалы после встречи</p><button type="button" onClick={() => onChange({ ...value, materials: [...value.materials, { title: "", url: "" }] })} className="text-xs text-white/50">+ Добавить</button></div>{value.materials.map((item, index) => <div key={index} className="mb-2 grid gap-2 sm:grid-cols-2"><input value={item.title} onChange={(e) => onChange({ ...value, materials: value.materials.map((current, itemIndex) => itemIndex === index ? { ...current, title: e.target.value } : current) })} placeholder="Название" className="workspace-input" /><input type="url" value={item.url} onChange={(e) => onChange({ ...value, materials: value.materials.map((current, itemIndex) => itemIndex === index ? { ...current, url: e.target.value } : current) })} placeholder="https://…" className="workspace-input" /></div>)}</div><div className="flex gap-2 sm:col-span-2"><button className="workspace-button">Сохранить итоги</button><button type="button" onClick={onClose} className="workspace-button !bg-transparent !text-white">Закрыть</button></div></form>;
}

function AttendancePanel({ attendees, eventId, onMark }: { attendees: Attendee[]; eventId: number; onMark: (eventId: number, membershipId: number, status: "present" | "absent" | "excused") => void }) {
  return <div className="mt-5 border-t border-white/8 pt-5">{!attendees.length ? <p className="text-sm text-white/35">Зачисленных резидентов пока нет.</p> : <div className="space-y-2">{attendees.map((resident) => <div key={resident.membership_id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-black/25 p-3"><div><p className="text-sm">{resident.name}</p><p className="text-xs text-white/35">{resident.email} · {resident.status === "present" ? "присутствовал" : resident.status === "absent" ? "отсутствовал" : resident.status === "excused" ? "уважительная причина" : "не отмечен"}</p></div><div className="flex gap-2"><button type="button" onClick={() => void onMark(eventId, resident.membership_id, "present")} className="rounded-full border border-white/10 p-2 text-emerald-300" aria-label="Присутствовал"><Check size={15} /></button><button type="button" onClick={() => void onMark(eventId, resident.membership_id, "absent")} className="rounded-full border border-white/10 px-3 py-2 text-xs text-white/50">Нет</button><button type="button" onClick={() => void onMark(eventId, resident.membership_id, "excused")} className="rounded-full border border-white/10 px-3 py-2 text-xs text-white/50">Уваж.</button></div></div>)}</div>}</div>;
}
