"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Award, Download, Loader2, Plus, RefreshCw, Search, Star, Trash2, Upload } from "lucide-react";

import { deleteAuth, describeApiError, getAuthJson, patchAuthJson, postAuthJson, putAuthJson } from "@/lib/api";
import { useAuth } from "@/lib/hooks/useAuth";

type Criterion = { key: string; label: string; description?: string | null; weight: number; max_score: number };
type Evaluation = { id: number; expert: { id: number; name: string }; scores: Record<string, number>; normalized_score: number; comment?: string | null; recommendation: string };
type DemoProject = {
  id: number; membership_id: number; resident: { id: number; name: string; email?: string }; project: { id: number; name: string; readiness_index: number };
  selection_reason?: string | null; pitch_title?: string | null; summary?: string | null; presentation_url?: string | null; video_url?: string | null;
  attachments: string[]; submitted_at?: string | null; evaluation_count: number; average_score?: number | null; score_adjustment?: number | null;
  manager_note?: string | null; outcome?: string | null; final_score?: number | null; rank?: number | null; evaluations: Evaluation[];
};
type DemoDay = { id: number; title: string; description?: string | null; starts_at?: string | null; criteria: Criterion[]; status: "draft" | "open" | "scoring" | "finalized"; access_role: string; experts: Array<{ id: number; user_id: number; name: string; email?: string }>; projects: DemoProject[]; finalized_at?: string | null };
type DemoDaysResponse = { access_role: string; demo_days: DemoDay[] };
type ResidentOption = { membership_id: number; name: string; email?: string; status: string };
type Candidate = { id: number; name: string; email: string };

const defaultCriteria: Criterion[] = [
  { key: "problem", label: "Проблема и ценность", weight: 30, max_score: 10 },
  { key: "market", label: "Рынок и клиенты", weight: 25, max_score: 10 },
  { key: "traction", label: "Подтверждение и динамика", weight: 25, max_score: 10 },
  { key: "team", label: "Команда и исполнение", weight: 20, max_score: 10 },
];
const statusLabel = { draft: "Черновик", open: "Сбор материалов", scoring: "Оценивание", finalized: "Результаты опубликованы" };
const outcomeLabel = { winner: "Победитель", finalist: "Финалист", participant: "Участник", not_selected: "Не прошёл финальный отбор" };

export function DemoDayWorkspace({ cohortId, membershipId, residents = [], token: providedToken, canManage = false }: { cohortId: number; membershipId?: number; residents?: ResidentOption[]; token?: string; canManage?: boolean }) {
  const auth = useAuth(); const token = providedToken || auth.token;
  const [data, setData] = useState<DemoDaysResponse | null>(null); const [demoDayId, setDemoDayId] = useState("");
  const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  const [createForm, setCreateForm] = useState({ title: "Демо-день", description: "", startsAt: "" });
  const [criteria, setCriteria] = useState<Criterion[]>(defaultCriteria);
  const [membershipToAdd, setMembershipToAdd] = useState(""); const [selectionReason, setSelectionReason] = useState("");
  const [expertQuery, setExpertQuery] = useState(""); const [candidates, setCandidates] = useState<Candidate[]>([]);

  const load = useCallback(async () => {
    if (!token) return; setBusy("load"); setError("");
    try {
      const path = membershipId ? `/api/accelerators/memberships/${membershipId}/demo-days` : `/api/accelerators/cohorts/${cohortId}/demo-days`;
      const response = await getAuthJson<DemoDaysResponse>(path, token); setData(response);
      setDemoDayId((current) => current && response.demo_days.some((row) => String(row.id) === current) ? current : String(response.demo_days[0]?.id || ""));
    } catch (reason) { setError(describeApiError(reason, "Не удалось загрузить демо-день")); }
    finally { setBusy(""); }
  }, [cohortId, membershipId, token]);
  useEffect(() => { void load(); }, [load]);
  const active = useMemo(() => data?.demo_days.find((row) => String(row.id) === demoDayId) || data?.demo_days[0] || null, [data, demoDayId]);
  const isManager = canManage || data?.access_role === "global_admin" || data?.access_role === "organizer";
  const isExpert = data?.access_role === "expert";

  const createDemoDay = async (event: FormEvent) => { event.preventDefault(); if (!token) return; setBusy("create"); setError(""); try { const row = await postAuthJson<DemoDay>(`/api/accelerators/cohorts/${cohortId}/demo-days`, { title: createForm.title, description: createForm.description || null, starts_at: createForm.startsAt ? new Date(createForm.startsAt).toISOString() : null, criteria }, token); await load(); setDemoDayId(String(row.id)); } catch (reason) { setError(describeApiError(reason, "Не удалось создать демо-день")); } finally { setBusy(""); } };
  const addProject = async () => { if (!token || !active || !membershipToAdd) return; setBusy("project"); try { await postAuthJson(`/api/accelerators/demo-days/${active.id}/projects`, { membership_id: Number(membershipToAdd), selection_reason: selectionReason || null }, token); setMembershipToAdd(""); setSelectionReason(""); await load(); } catch (reason) { setError(describeApiError(reason, "Не удалось добавить проект. Проверьте, что резидент завершил хотя бы один этап.")); } finally { setBusy(""); } };
  const removeProject = async (id: number) => { if (!token || !window.confirm("Убрать проект из демо-дня?")) return; setBusy(`remove-project-${id}`); try { await deleteAuth(`/api/accelerators/demo-day-projects/${id}`, token); await load(); } catch (reason) { setError(describeApiError(reason, "Не удалось убрать проект")); } finally { setBusy(""); } };
  const searchExperts = async () => { if (!token || expertQuery.trim().length < 2) return; setBusy("search"); try { setCandidates(await getAuthJson<Candidate[]>(`/api/accelerators/cohorts/${cohortId}/demo-day-expert-candidates?q=${encodeURIComponent(expertQuery)}`, token)); } catch (reason) { setError(describeApiError(reason, "Не удалось найти экспертов")); } finally { setBusy(""); } };
  const addExpert = async (userId: number) => { if (!token || !active) return; setBusy(`expert-${userId}`); try { await postAuthJson(`/api/accelerators/demo-days/${active.id}/experts`, { user_id: userId }, token); setCandidates([]); setExpertQuery(""); await load(); } catch (reason) { setError(describeApiError(reason, "Не удалось пригласить эксперта")); } finally { setBusy(""); } };
  const removeExpert = async (userId: number) => { if (!token || !active) return; setBusy(`remove-expert-${userId}`); try { await deleteAuth(`/api/accelerators/demo-days/${active.id}/experts/${userId}`, token); await load(); } catch (reason) { setError(describeApiError(reason, "Не удалось убрать эксперта")); } finally { setBusy(""); } };
  const advanceStatus = async () => { if (!token || !active) return; const next = active.status === "draft" ? "open" : active.status === "open" ? "scoring" : "finalized"; if (next === "finalized" && !window.confirm("Зафиксировать рейтинг и опубликовать результаты? После этого оценки изменить нельзя.")) return; setBusy("status"); try { await patchAuthJson(`/api/accelerators/demo-days/${active.id}/status`, { status: next }, token); await load(); } catch (reason) { setError(describeApiError(reason, "Не удалось изменить этап демо-дня")); } finally { setBusy(""); } };
  const download = async (format: "csv" | "json") => { if (!token || !active) return; setBusy(`export-${format}`); try { const headers: Record<string, string> = { "x-pitchy-api": "1" }; if (token !== "cookie-session") headers.Authorization = `Bearer ${token}`; const response = await fetch(`/api/accelerators/demo-days/${active.id}/export?format=${format}`, { headers, credentials: "include" }); if (!response.ok) throw new Error("export_failed"); const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = format === "csv" ? `demo-day-${active.id}-results.csv` : `demo-day-${active.id}-project-cards.json`; anchor.click(); URL.revokeObjectURL(url); } catch { setError("Не удалось скачать результаты демо-дня."); } finally { setBusy(""); } };

  if (busy === "load" && !data) return <section className="workspace-card grid place-items-center py-14"><Loader2 className="animate-spin text-white/35" /></section>;
  if (isManager && !data?.demo_days.length) return <form onSubmit={createDemoDay} className="workspace-card"><h2 className="text-xl">Создать демо-день</h2><p className="mt-1 text-sm text-white/40">Настройте критерии до открытия сбора материалов.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><Field label="Название"><input value={createForm.title} onChange={(event) => setCreateForm({ ...createForm, title: event.target.value })} required minLength={2} className="workspace-input mt-2" /></Field><Field label="Дата и время"><input type="datetime-local" value={createForm.startsAt} onChange={(event) => setCreateForm({ ...createForm, startsAt: event.target.value })} className="workspace-input mt-2" /></Field><Field label="Описание" wide><textarea value={createForm.description} onChange={(event) => setCreateForm({ ...createForm, description: event.target.value })} rows={3} className="workspace-input mt-2 resize-y" /></Field></div><CriteriaEditor criteria={criteria} onChange={setCriteria} /><button disabled={busy === "create"} className="workspace-button mt-5"><Award size={15} /> Создать демо-день</button>{error && <ErrorText>{error}</ErrorText>}</form>;
  if (!active) return <section className="workspace-card py-12 text-center"><Award className="mx-auto text-white/25" /><h2 className="mt-4 text-xl">Проект ещё не отобран</h2><p className="mt-2 text-sm text-white/40">Организатор сообщит, когда проект появится в демо-дне.</p></section>;

  return <div className="space-y-5"><section className="workspace-card"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-wide text-white/30">{statusLabel[active.status]}</p><h2 className="mt-1 text-2xl">{active.title}</h2><p className="mt-2 text-sm text-white/45">{active.description || "Финальная презентация проектов потока"}</p></div><div className="flex flex-wrap gap-2">{data && data.demo_days.length > 1 && <select value={demoDayId} onChange={(event) => setDemoDayId(event.target.value)} className="workspace-input !w-auto">{data.demo_days.map((row) => <option key={row.id} value={row.id}>{row.title}</option>)}</select>}<button type="button" onClick={() => void load()} className="rounded-full border border-white/10 p-3 text-white/40"><RefreshCw size={16} /></button></div></div>{isManager && active.status !== "finalized" && <button type="button" onClick={() => void advanceStatus()} disabled={busy === "status"} className="workspace-button mt-5">{active.status === "draft" ? "Открыть сбор материалов" : active.status === "open" ? "Начать оценивание" : "Финализировать рейтинг"}</button>}{active.status === "finalized" && isManager && <div className="mt-5 flex flex-wrap gap-2"><button type="button" onClick={() => void download("csv")} className="workspace-button"><Download size={15} /> Результаты CSV</button><button type="button" onClick={() => void download("json")} className="workspace-button !bg-transparent !text-white"><Download size={15} /> Карточки проектов JSON</button></div>}</section>

    {isManager && active.status !== "finalized" && <div className="grid gap-5 lg:grid-cols-2"><section className="workspace-card"><h3 className="text-lg">Отбор проектов</h3><p className="mt-1 text-xs text-white/35">Доступны только зачисленные резиденты с завершённым этапом.</p><select value={membershipToAdd} onChange={(event) => setMembershipToAdd(event.target.value)} className="workspace-input mt-4"><option value="">Выберите резидента</option>{residents.filter((row) => row.status === "enrolled" && !active.projects.some((project) => project.membership_id === row.membership_id)).map((row) => <option key={row.membership_id} value={row.membership_id}>{row.name}</option>)}</select><input value={selectionReason} onChange={(event) => setSelectionReason(event.target.value)} placeholder="Причина отбора" className="workspace-input mt-3" /><button type="button" onClick={() => void addProject()} disabled={!membershipToAdd || busy === "project"} className="workspace-button mt-3"><Plus size={15} /> Добавить проект</button></section><section className="workspace-card"><h3 className="text-lg">Экспертное жюри</h3><div className="mt-4 flex gap-2"><input value={expertQuery} onChange={(event) => setExpertQuery(event.target.value)} placeholder="Имя или email" className="workspace-input" /><button type="button" onClick={() => void searchExperts()} className="workspace-button"><Search size={15} /></button></div>{candidates.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{candidates.map((candidate) => <button type="button" key={candidate.id} onClick={() => void addExpert(candidate.id)} className="rounded-full border border-white/10 px-3 py-2 text-sm text-white/60">{candidate.name} · {candidate.email}</button>)}</div>}<div className="mt-4 space-y-2">{active.experts.map((expert) => <div key={expert.user_id} className="flex items-center justify-between rounded-xl bg-black/20 p-3"><div><p>{expert.name}</p><p className="text-xs text-white/35">{expert.email}</p></div>{active.status !== "scoring" && <button type="button" onClick={() => void removeExpert(expert.user_id)} className="text-white/35"><Trash2 size={15} /></button>}</div>)}</div></section></div>}

    <section className="workspace-card"><h3 className="text-xl">{active.status === "finalized" ? "Итоговый рейтинг" : "Проекты"}</h3><div className="mt-5 space-y-4">{active.projects.map((project) => <article key={project.id} className="rounded-2xl border border-white/9 p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs text-white/30">{active.status === "finalized" ? `Место ${project.rank}` : project.resident.name}</p><h4 className="mt-1 text-lg">{project.pitch_title || project.project.name}</h4><p className="mt-1 text-xs text-white/35">Паспорт заполнен на {project.project.readiness_index}% · оценок {project.evaluation_count}</p></div>{active.status === "finalized" && <div className="text-right"><p className="text-2xl">{project.final_score}</p><p className="text-xs text-white/35">{outcomeLabel[project.outcome as keyof typeof outcomeLabel] || project.outcome}</p></div>}{isManager && active.status !== "scoring" && active.status !== "finalized" && <button type="button" onClick={() => void removeProject(project.id)} className="text-white/30"><Trash2 size={15} /></button>}</div>{project.summary && <p className="mt-3 text-sm text-white/55">{project.summary}</p>}{project.presentation_url && <div className="mt-3 flex flex-wrap gap-3 text-sm"><a href={project.presentation_url} target="_blank" rel="noreferrer" className="text-sky-300">Презентация ↗</a>{project.video_url && <a href={project.video_url} target="_blank" rel="noreferrer" className="text-sky-300">Видео ↗</a>}</div>}{(data?.access_role === "resident" || isManager) && active.status === "open" && <MaterialsForm project={project} token={token!} onSaved={load} />}{isExpert && active.status === "scoring" && <ScoreForm demoDay={active} project={project} token={token!} onSaved={load} />}{isManager && active.status !== "finalized" && <DecisionForm project={project} token={token!} onSaved={load} />}{active.status === "finalized" && project.evaluations.length > 0 && <div className="mt-4 space-y-2">{project.evaluations.map((evaluation) => <div key={evaluation.id} className="rounded-xl bg-black/20 p-3"><p className="text-sm">{evaluation.expert.name}: {evaluation.normalized_score}/100</p>{evaluation.comment && <p className="mt-1 text-xs text-white/40">{evaluation.comment}</p>}</div>)}</div>}</article>)}{!active.projects.length && <p className="py-8 text-center text-sm text-white/35">Проекты ещё не отобраны.</p>}</div></section>{error && <ErrorText>{error}</ErrorText>}</div>;
}

function CriteriaEditor({ criteria, onChange }: { criteria: Criterion[]; onChange: (rows: Criterion[]) => void }) { return <div className="mt-6"><div className="flex items-center justify-between"><h3 className="text-sm text-white/60">Критерии оценки</h3><button type="button" onClick={() => onChange([...criteria, { key: `criterion_${criteria.length + 1}`, label: "Новый критерий", weight: 10, max_score: 10 }])} disabled={criteria.length >= 10} className="text-xs text-white/40">+ Добавить</button></div><div className="mt-3 space-y-2">{criteria.map((criterion, index) => <div key={criterion.key} className="grid gap-2 rounded-xl border border-white/8 p-3 sm:grid-cols-[1fr_100px_auto]"><input value={criterion.label} onChange={(event) => onChange(criteria.map((row, rowIndex) => rowIndex === index ? { ...row, label: event.target.value } : row))} className="workspace-input" /><input type="number" min={1} max={100} value={criterion.weight} onChange={(event) => onChange(criteria.map((row, rowIndex) => rowIndex === index ? { ...row, weight: Number(event.target.value) } : row))} className="workspace-input" aria-label={`Вес ${criterion.label}`} /><button type="button" onClick={() => onChange(criteria.filter((_, rowIndex) => rowIndex !== index))} disabled={criteria.length === 1} className="text-white/30"><Trash2 size={14} /></button></div>)}</div></div>; }

function MaterialsForm({ project, token, onSaved }: { project: DemoProject; token: string; onSaved: () => Promise<void> }) { const [form, setForm] = useState({ title: project.pitch_title || project.project.name, summary: project.summary || "", presentation: project.presentation_url || "", video: project.video_url || "", attachments: project.attachments.join(", ") }); const [busy, setBusy] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await patchAuthJson(`/api/accelerators/demo-day-projects/${project.id}/materials`, { pitch_title: form.title, summary: form.summary, presentation_url: form.presentation, video_url: form.video || null, attachments: form.attachments.split(",").map((row) => row.trim()).filter(Boolean) }, token); await onSaved(); } finally { setBusy(false); } }; return <form onSubmit={submit} className="mt-4 grid gap-3 rounded-xl bg-white/[.025] p-3 sm:grid-cols-2"><input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} required minLength={2} className="workspace-input sm:col-span-2" placeholder="Название питча" /><textarea value={form.summary} onChange={(event) => setForm({ ...form, summary: event.target.value })} required minLength={2} rows={3} className="workspace-input resize-y sm:col-span-2" placeholder="Краткое описание проекта" /><input type="url" value={form.presentation} onChange={(event) => setForm({ ...form, presentation: event.target.value })} required className="workspace-input" placeholder="Ссылка на презентацию" /><input type="url" value={form.video} onChange={(event) => setForm({ ...form, video: event.target.value })} className="workspace-input" placeholder="Ссылка на видео" /><input value={form.attachments} onChange={(event) => setForm({ ...form, attachments: event.target.value })} className="workspace-input sm:col-span-2" placeholder="Дополнительные ссылки через запятую" /><button disabled={busy} className="workspace-button sm:col-span-2"><Upload size={14} /> Сохранить материалы</button></form>; }

function ScoreForm({ demoDay, project, token, onSaved }: { demoDay: DemoDay; project: DemoProject; token: string; onSaved: () => Promise<void> }) { const existing = project.evaluations[0]; const [scores, setScores] = useState<Record<string, number>>(existing?.scores || Object.fromEntries(demoDay.criteria.map((row) => [row.key, 0]))); const [comment, setComment] = useState(existing?.comment || ""); const [recommendation, setRecommendation] = useState(existing?.recommendation || "consider"); const [busy, setBusy] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await putAuthJson(`/api/accelerators/demo-day-projects/${project.id}/score`, { scores, comment: comment || null, recommendation }, token); await onSaved(); } finally { setBusy(false); } }; return <form onSubmit={submit} className="mt-4 rounded-xl border border-violet-400/15 bg-violet-400/[.04] p-3"><h5 className="flex items-center gap-2"><Star size={15} /> Ваша оценка</h5><div className="mt-3 grid gap-3 sm:grid-cols-2">{demoDay.criteria.map((criterion) => <label key={criterion.key} className="text-xs text-white/50">{criterion.label}<input type="number" min={0} max={criterion.max_score} step="0.5" value={scores[criterion.key] ?? 0} onChange={(event) => setScores({ ...scores, [criterion.key]: Number(event.target.value) })} className="workspace-input mt-1" /></label>)}</div><textarea value={comment} onChange={(event) => setComment(event.target.value)} rows={2} className="workspace-input mt-3 resize-y" placeholder="Комментарий проекту" /><select value={recommendation} onChange={(event) => setRecommendation(event.target.value)} className="workspace-input mt-3"><option value="advance">Рекомендовать дальше</option><option value="consider">Рассмотреть</option><option value="decline">Не рекомендовать</option></select><button disabled={busy} className="workspace-button mt-3"><Star size={14} /> Отправить оценку</button></form>; }

function DecisionForm({ project, token, onSaved }: { project: DemoProject; token: string; onSaved: () => Promise<void> }) { const [adjustment, setAdjustment] = useState(project.score_adjustment || 0); const [outcome, setOutcome] = useState(project.outcome || "participant"); const [note, setNote] = useState(project.manager_note || ""); const save = async () => { await patchAuthJson(`/api/accelerators/demo-day-projects/${project.id}/decision`, { score_adjustment: adjustment, outcome, manager_note: note || null }, token); await onSaved(); }; return <div className="mt-4 grid gap-2 rounded-xl bg-black/20 p-3 sm:grid-cols-[120px_180px_1fr_auto]"><input type="number" min={-20} max={20} step="0.5" value={adjustment} onChange={(event) => setAdjustment(Number(event.target.value))} className="workspace-input" aria-label="Корректировка оценки" /><select value={outcome} onChange={(event) => setOutcome(event.target.value)} className="workspace-input"><option value="winner">Победитель</option><option value="finalist">Финалист</option><option value="participant">Участник</option><option value="not_selected">Не прошёл отбор</option></select><input value={note} onChange={(event) => setNote(event.target.value)} className="workspace-input" placeholder="Решение организатора" /><button type="button" onClick={() => void save()} className="workspace-button">Сохранить</button></div>; }

function Field({ label, wide, children }: { label: string; wide?: boolean; children: React.ReactNode }) { return <label className={`text-sm text-white/55 ${wide ? "sm:col-span-2" : ""}`}>{label}{children}</label>; }
function ErrorText({ children }: { children: React.ReactNode }) { return <p role="alert" className="rounded-2xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-200">{children}</p>; }
