"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, ChevronRight, History, Loader2, RotateCcw, X } from "lucide-react";
import { describeApiError, getAuthJson, patchAuthJson } from "@/lib/api";

type QueueItem = { id:number; membership_id:number; team_id?:number|null; resident:{name:string;email:string}; answer_text?:string|null; attachments:string[]; score?:number|null; passed?:boolean|null; display_status:"review_pending"|"needs_revision"|"accepted"; attempt_count:number; submitted_at:string; review_comment?:string|null; assignment:{id:number;title:string;stage_id?:number|null;assignment_type:"quiz"|"text_files";submission_mode:"individual"|"team";due_at?:string|null;passing_score?:number|null;max_attempts:number}; team?:{id:number;name:string}|null; trackers:Array<{id:number;name:string}> };
type Attempt={id:number;attempt_number:number;answer_text?:string|null;attachments:string[];score?:number|null;passed?:boolean|null;review_status?:string|null;review_comment?:string|null;created_at:string;quiz_results:Array<{question_id:string;prompt:string;selected_option_label?:string|null;correct_option_label?:string|null;correct:boolean}>};
type Filters={stage:string;assignment:string;participant:string;team:string;tracker:string;status:string};
const STATUS:Record<string,string>={review_pending:"На проверке",needs_revision:"На доработке",accepted:"Принято"};

export function HomeworkReviewQueue({cohortId,token,initialAssignmentId}:{cohortId:number;token:string;initialAssignmentId?:number}){
  const [items,setItems]=useState<QueueItem[]>([]); const [filters,setFilters]=useState<Filters>({stage:"",assignment:initialAssignmentId?String(initialAssignmentId):"",participant:"",team:"",tracker:"",status:"review_pending"}); const [selected,setSelected]=useState<QueueItem|null>(null); const [comment,setComment]=useState(""); const [attempts,setAttempts]=useState<Attempt[]>([]); const [historyOpen,setHistoryOpen]=useState(false); const [busy,setBusy]=useState(""); const [error,setError]=useState("");
  const load=useCallback(async()=>{setError("");try{const data=await getAuthJson<{items:QueueItem[]}>(`/api/accelerators/cohorts/${cohortId}/homework-review-queue`,token);setItems(data.items);setSelected((current)=>current?data.items.find((row)=>row.id===current.id)||null:null);}catch(reason){setError(describeApiError(reason,"Не удалось загрузить очередь проверки"));}},[cohortId,token]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setSelected(null);};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close);},[]);
  const options=useMemo(()=>({stages:Array.from(new Set(items.map((row)=>row.assignment.stage_id).filter(Boolean))),assignments:Array.from(new Map(items.map((row)=>[row.assignment.id,row.assignment])).values()),participants:Array.from(new Map(items.map((row)=>[row.membership_id,row.resident])).entries()),teams:Array.from(new Map(items.filter((row)=>row.team).map((row)=>[row.team!.id,row.team!])).values()),trackers:Array.from(new Map(items.flatMap((row)=>row.trackers.map((tracker)=>[tracker.id,tracker] as const))).values())}),[items]);
  const visible=useMemo(()=>items.filter((row)=>(!filters.stage||String(row.assignment.stage_id)===filters.stage)&&(!filters.assignment||String(row.assignment.id)===filters.assignment)&&(!filters.participant||String(row.membership_id)===filters.participant)&&(!filters.team||String(row.team_id)===filters.team)&&(!filters.tracker||row.trackers.some((tracker)=>String(tracker.id)===filters.tracker))&&(!filters.status||row.display_status===filters.status)),[filters,items]);
  const review=async(status:"accepted"|"needs_revision")=>{if(!selected)return;setBusy("review");try{await patchAuthJson(`/api/accelerators/homework/submissions/${selected.id}/review`,{status,comment:comment||null},token);setComment("");await load();}catch(reason){setError(describeApiError(reason,"Не удалось сохранить решение"));}finally{setBusy("");}};
  const showHistory=async()=>{if(!selected)return;setHistoryOpen((value)=>!value);if(attempts.length)return;setBusy("history");try{setAttempts(await getAuthJson<Attempt[]>(`/api/accelerators/homework/submissions/${selected.id}/attempts`,token));}catch(reason){setError(describeApiError(reason,"Не удалось загрузить историю попыток"));}finally{setBusy("");}};
  const open=(item:QueueItem)=>{setSelected(item);setComment("");setAttempts([]);setHistoryOpen(false);};
  const patch=(key:keyof Filters,value:string)=>setFilters((current)=>({...current,[key]:value}));

  return <section className="workspace-card">
    <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><Filter label="Этап" value={filters.stage} onChange={(v)=>patch("stage",v)} options={options.stages.map((id)=>[String(id),`Этап #${id}`])}/><Filter label="Задание" value={filters.assignment} onChange={(v)=>patch("assignment",v)} options={options.assignments.map((row)=>[String(row.id),row.title])}/><Filter label="Участник" value={filters.participant} onChange={(v)=>patch("participant",v)} options={options.participants.map(([id,row])=>[String(id),row.name])}/><Filter label="Команда" value={filters.team} onChange={(v)=>patch("team",v)} options={options.teams.map((row)=>[String(row.id),row.name])}/><Filter label="Трекер" value={filters.tracker} onChange={(v)=>patch("tracker",v)} options={options.trackers.map((row)=>[String(row.id),row.name])}/><Filter label="Статус" value={filters.status} onChange={(v)=>patch("status",v)} options={Object.entries(STATUS)}/></div>
    {error&&<p role="alert" className="mt-4 rounded-xl bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}
    <div className="mt-5 overflow-hidden rounded-2xl border border-white/9">{visible.map((item)=><button type="button" key={item.id} onClick={()=>open(item)} className="grid w-full gap-3 border-b border-white/8 p-4 text-left last:border-0 md:grid-cols-[1fr_1.1fr_130px_150px_auto] md:items-center"><span><span className="block text-sm">{item.resident.name}</span><span className="block text-xs text-white/35">{item.team?.name||item.resident.email}</span></span><span className="text-sm text-white/55">{item.assignment.title}</span><span className="text-xs text-white/45">Попытка {item.attempt_count}{item.score!=null?` · ${item.score}%`:""}</span><span className="text-xs text-white/45">{new Date(item.submitted_at).toLocaleString("ru-RU")}</span><ChevronRight size={16} className="text-white/30"/></button>)}{!visible.length&&<p className="py-12 text-center text-sm text-white/35">По выбранным фильтрам ответов нет.</p>}</div>
    {selected&&<div className="fixed inset-0 z-[80] flex justify-end bg-black/65" role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget)setSelected(null);}}><aside role="dialog" aria-modal="true" aria-labelledby="review-title" className="flex h-full w-full max-w-2xl flex-col border-l border-white/10 bg-[#1c1b1b] shadow-2xl"><header className="flex items-start justify-between border-b border-white/8 p-5"><div><p className="text-xs text-white/35">{selected.assignment.title}</p><h2 id="review-title" className="mt-1 text-2xl">{selected.resident.name}</h2><p className="mt-1 text-xs text-white/40">Попытка {selected.attempt_count} · {STATUS[selected.display_status]}</p></div><button type="button" onClick={()=>setSelected(null)}><X className="text-white/45"/></button></header><div className="flex-1 overflow-y-auto p-5">{selected.score!=null&&<p className={`rounded-xl p-3 text-sm ${selected.passed?"bg-emerald-400/10 text-emerald-200":"bg-amber-400/10 text-amber-200"}`}>Результат теста: {selected.score}% · {selected.passed?"пройден":"не пройден"}</p>}{selected.answer_text&&<div className="mt-5"><p className="text-xs uppercase tracking-[.16em] text-white/35">Ответ</p><p className="mt-3 whitespace-pre-wrap text-sm leading-relaxed text-white/65">{selected.answer_text}</p></div>}{selected.attachments.length>0&&<div className="mt-5 space-y-2">{selected.attachments.map((url,index)=><a key={url} href={url} target="_blank" rel="noreferrer" className="block rounded-xl border border-white/8 p-3 text-sm text-blue-200">Вложение {index+1}</a>)}</div>}{selected.review_comment&&<p className="mt-5 rounded-xl bg-white/[.04] p-3 text-sm text-white/50">Предыдущий комментарий: {selected.review_comment}</p>}<button type="button" onClick={()=>void showHistory()} className="mt-6 inline-flex items-center gap-2 text-sm text-white/55"><History size={14}/>История попыток</button>{historyOpen&&<AttemptHistory rows={attempts} loading={busy==="history"}/>}</div>{selected.assignment.assignment_type==="text_files"&&<footer className="border-t border-white/8 p-5"><textarea value={comment} onChange={(event)=>setComment(event.target.value)} rows={3} placeholder="Комментарий участнику" className="workspace-input resize-y"/><div className="mt-3 flex justify-end gap-2"><button type="button" onClick={()=>void review("needs_revision")} disabled={busy==="review"} className="overview-secondary"><RotateCcw size={14}/>На доработку</button><button type="button" onClick={()=>void review("accepted")} disabled={busy==="review"} className="workspace-button"><CheckCircle2 size={14}/>Принять</button></div></footer>}</aside></div>}
  </section>;
}

function Filter({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:Array<[string,string]>}){return <label className="text-xs text-white/40">{label}<select aria-label={label} value={value} onChange={(event)=>onChange(event.target.value)} className="workspace-input mt-1"><option value="">Все</option>{options.map(([key,text])=><option key={key} value={key}>{text}</option>)}</select></label>}
function AttemptHistory({rows,loading}:{rows:Attempt[];loading:boolean}){if(loading)return <Loader2 className="mt-5 animate-spin text-white/40"/>;return <div className="mt-4 space-y-3">{rows.map((attempt)=><div key={attempt.id} className="rounded-xl bg-black/25 p-3"><p className="text-sm">Попытка {attempt.attempt_number}{attempt.score!=null?` · ${attempt.score}%`:""}</p>{attempt.answer_text&&<p className="mt-2 text-xs text-white/55">{attempt.answer_text}</p>}{attempt.review_comment&&<p className="mt-2 text-xs text-white/45">Комментарий: {attempt.review_comment}</p>}{attempt.quiz_results.map((result)=><p key={result.question_id} className={`mt-2 text-xs ${result.correct?"text-emerald-300":"text-amber-200"}`}>{result.correct?"✓":"×"} {result.prompt}: {result.selected_option_label||"нет ответа"}</p>)}</div>)}</div>}
