"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { CalendarDays, Check, ChevronDown, Loader2, LockKeyhole } from "lucide-react";
import { describeApiError, getAuthJson, postAuthJson } from "@/lib/api";
import { useAuth } from "@/lib/hooks/useAuth";

type Material={id:number;title:string;kind:"link"|"video"|"text";url?:string|null;content?:string|null;required:boolean;completed:boolean};
type Timeline={key:string;kind:"material"|"homework"|"event";id:number;title:string;sort_at?:string|null;required:boolean;status?:string|null;event_format?:string};
type Stage={id:number;title:string;description?:string|null;unlock_at?:string|null;due_at?:string|null;required:boolean;state:"locked"|"available"|"in_progress"|"completed"|"overdue"|"waived";completed_required:number;required_total:number;blockers:Array<{kind:string;id:number;title:string;reason:string}>;materials:Material[];timeline:Timeline[]};
type Section="homework"|"events"|"tools";
const stateLabel={locked:"Закрыт",available:"Доступен",in_progress:"В работе",completed:"Завершён",overdue:"Просрочен",waived:"Требование снято"};

export function ResidentProgramWorkspace({membershipId,onNavigate}:{membershipId:number;onNavigate:(section:Section,targetId?:number)=>void}){
 const {token}=useAuth();const [stages,setStages]=useState<Stage[]>([]);const [open,setOpen]=useState<number|null>(null);const [busy,setBusy]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 const load=useCallback(async()=>{if(!token)return;setError("");try{const rows=await getAuthJson<Stage[]>(`/api/accelerators/memberships/${membershipId}/program-stages`,token);setStages(rows.map(row=>({...row,blockers:row.blockers||[],materials:row.materials||[],timeline:row.timeline||[]})));const current=rows.find(row=>['available','in_progress','overdue'].includes(row.state));setOpen(current?.id||null)}catch(reason){setError(describeApiError(reason,"Не удалось загрузить программу"))}finally{setLoading(false)}},[membershipId,token]);
 useEffect(()=>{void load()},[load]);const completed=stages.filter(row=>row.state==='completed'||row.state==='waived').length;const current=stages.find(row=>['in_progress','overdue','available'].includes(row.state));const percent=stages.length?Math.round(completed/stages.length*100):0;
 const items=useMemo(()=>current?stageItems(current):[],[current]);const next=items.find(item=>!item.done);
 const completeMaterial=async(id:number)=>{if(!token)return;setBusy(`material-${id}`);try{await postAuthJson(`/api/accelerators/program/materials/${id}/complete`,{},token);await load()}catch(reason){setError(describeApiError(reason,"Не удалось отметить материал"))}finally{setBusy("")}};
 const action=(item:ReturnType<typeof stageItems>[number])=>{if(item.kind==='homework')onNavigate('homework',item.id);else if(item.kind==='event')onNavigate('events',item.id);else if(item.url)window.open(item.url,'_blank','noopener,noreferrer');else if(!item.done)void completeMaterial(item.id)};
 if(loading)return <div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-white/35"/></div>;
 return <section><header className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold">Мой путь</h1><p className="mt-1 text-sm text-white/45">{completed} из {stages.length} этапов завершено</p></div>{current?.due_at&&<p className="text-right text-sm text-white/45">Текущий этап<br/><b className="text-white">до {new Date(current.due_at).toLocaleDateString('ru-RU',{day:'numeric',month:'long'})}</b></p>}</header><div className="mt-4 flex items-center gap-3"><div className="h-2 flex-1 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-emerald-400" style={{width:`${percent}%`}}/></div><span className="text-sm text-white/55">{percent}%</span></div>
 {error&&<p role="alert" className="mt-5 rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-red-200">{error}</p>}
 {current&&<div className="mt-5 flex flex-wrap items-center gap-5 rounded-2xl border border-amber-300/25 bg-amber-300/[.04] p-5"><span className="grid size-11 place-items-center rounded-full border border-amber-300 text-lg text-amber-200">{stages.indexOf(current)+1}</span><div className="min-w-0 flex-1"><p className="text-xs uppercase tracking-wide text-amber-200">Сейчас</p><h2 className="mt-1 text-xl">{current.title}</h2><p className="mt-1 text-sm text-white/50">Выполнено {current.completed_required} из {current.required_total} обязательных действий</p>{next&&<p className="mt-1 text-sm text-white/70">Следующий шаг: {next.title}</p>}</div>{next&&<button type="button" onClick={()=>action(next)} className="workspace-button">{next.kind==='homework'?'Перейти к заданию':'Открыть'} →</button>}</div>}
 <h2 className="mt-6 text-lg">Этапы программы</h2><div className="mt-3 space-y-2">{stages.map((stage,index)=>{const expanded=open===stage.id;const locked=stage.state==='locked';const done=stage.state==='completed'||stage.state==='waived';const list=stageItems(stage);return <article key={stage.id} className={`overflow-hidden rounded-xl border ${stage===current?'border-amber-300/25':done?'border-emerald-300/15':'border-white/9'} ${locked?'opacity-65':''}`}><button type="button" onClick={()=>!locked&&setOpen(expanded?null:stage.id)} disabled={locked} className="flex w-full items-center gap-3 p-4 text-left"><span className={`grid size-8 place-items-center rounded-full border ${done?'border-emerald-300/25 bg-emerald-300/10 text-emerald-300':'border-white/15'}`}>{done?<Check size={15}/>:locked?<LockKeyhole size={14}/>:index+1}</span><span className="min-w-0 flex-1"><b className="block truncate text-sm">{stage.title}</b>{stage.required_total>0&&<small className="text-white/35">{stage.completed_required} из {stage.required_total}{stage.due_at?` · до ${new Date(stage.due_at).toLocaleDateString('ru-RU')}`:''}</small>}</span><span className="text-xs text-white/45">{stateLabel[stage.state]}</span>{!locked&&<ChevronDown size={16} className={`text-white/35 ${expanded?'rotate-180':''}`}/>}</button>{expanded&&<div className="mx-4 mb-4 rounded-xl border border-white/8 p-4"><h3 className="text-sm font-medium">Что нужно сделать</h3><div className="mt-3 space-y-1">{list.map(item=><div key={item.key} className="flex items-center gap-3 py-2"><span className={`grid size-5 place-items-center rounded-full border ${item.done?'border-emerald-300 bg-emerald-300 text-black':'border-white/20'}`}>{item.done&&<Check size={12}/>}</span><span className={`min-w-0 flex-1 text-sm ${item.done?'text-white/45':''}`}>{item.title}</span>{!item.done&&<button type="button" onClick={()=>action(item)} disabled={busy===`material-${item.id}`} className="overview-secondary !px-3 !py-1.5">{item.kind==='homework'?'Перейти':'Открыть'}</button>}</div>)}{!list.length&&<p className="text-sm text-white/35">В этом этапе пока нет действий.</p>}</div></div>}</article>})}</div>{!stages.length&&<div className="mt-8 py-16 text-center"><CalendarDays className="mx-auto text-white/20"/><p className="mt-3">Организатор ещё не опубликовал программу.</p></div>}</section>;
}
function stageItems(stage:Stage){const materials=stage.materials.map(row=>({key:`material-${row.id}`,kind:'material' as const,id:row.id,title:row.title,done:row.completed,url:row.url||null}));const timeline=stage.timeline.filter(row=>row.kind!=='material').map(row=>({key:row.key,kind:row.kind,id:row.id,title:row.title,done:['accepted','completed','attended'].includes(row.status||''),url:null as string|null}));return [...materials,...timeline]}
