"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Check, ChevronDown, Loader2, RefreshCw, Send } from "lucide-react";
import { describeApiError, getAuthJson, patchAuthJson, postAuthJson } from "@/lib/api";
import { useAuth } from "@/lib/hooks/useAuth";
import { notifySuccess } from "@/lib/ui";

type Task={id:number;title:string;description?:string|null;status:"open"|"done"|"cancelled";due_at?:string|null};
type Checkin={id:number;period_start:string;health:string;summary:string;next_steps:string;blockers?:string|null;help_needed?:string|null};
type Feedback={id:number;body:string;created_at:string;author:{name:string}};
type Detail={risk:{level:string;reasons:string[]};checkins:Checkin[];feedback:Feedback[];tasks:Task[]};
type Tab="checkin"|"tasks"|"feedback"|"history";
const emptyForm={health:"green",summary:"",blockers:"",nextSteps:"",helpNeeded:""};

export function ResidentTracking({membershipId,focusTaskId}:{membershipId:number;focusTaskId?:number|null}){
 const {token}=useAuth();const [detail,setDetail]=useState<Detail|null>(null);const [tab,setTab]=useState<Tab>("checkin");const [form,setForm]=useState(emptyForm);const [extra,setExtra]=useState(false);const [busy,setBusy]=useState("");const [error,setError]=useState("");const draftKey=`accelerator-checkin-${membershipId}`;
 const load=useCallback(async()=>{if(!token)return;setError("");try{setDetail(await getAuthJson<Detail>(`/api/accelerators/memberships/${membershipId}/tracking`,token));}catch(reason){setError(describeApiError(reason,"Не удалось загрузить трекинг"));}},[membershipId,token]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{if(focusTaskId)setTab("tasks")},[focusTaskId]);useEffect(()=>{try{const saved=localStorage.getItem(draftKey);if(saved)setForm({...emptyForm,...JSON.parse(saved)})}catch{}},[draftKey]);useEffect(()=>{const timer=setTimeout(()=>{if(form.summary||form.nextSteps||form.blockers||form.helpNeeded)localStorage.setItem(draftKey,JSON.stringify(form))},350);return()=>clearTimeout(timer)},[draftKey,form]);
 const latest=detail?.checkins[0];const openTasks=useMemo(()=>detail?.tasks.filter(t=>t.status==="open")||[],[detail]);
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!token)return;setBusy("checkin");try{await postAuthJson(`/api/accelerators/memberships/${membershipId}/checkins`,{health:form.health,summary:form.summary,blockers:form.blockers||null,next_steps:form.nextSteps,help_needed:form.helpNeeded||null},token);localStorage.removeItem(draftKey);setForm(emptyForm);await load();notifySuccess("Еженедельный чек-ин отправлен трекеру")}catch(reason){setError(describeApiError(reason,"Не удалось отправить чек-ин"))}finally{setBusy("")}};
 const taskStatus=async(task:Task,status:"open"|"done")=>{if(!token)return;setBusy(`task-${task.id}`);try{await patchAuthJson(`/api/accelerators/tracking-tasks/${task.id}`,{status},token);await load()}catch(reason){setError(describeApiError(reason,"Не удалось изменить задачу"))}finally{setBusy("")}};
 if(!detail)return <section className="grid min-h-64 place-items-center">{error?<p className="text-red-200">{error}</p>:<Loader2 className="animate-spin text-white/40"/>}</section>;
 return <section><header className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold">Трекинг</h1><p className="mt-1 text-sm text-white/45">Чек-ин, задачи и обратная связь от трекера</p></div><button type="button" onClick={()=>void load()} aria-label="Обновить" className="overview-secondary"><RefreshCw size={15}/></button></header>
 <div className="mt-5 grid overflow-hidden rounded-2xl border border-white/9 sm:grid-cols-3"><Summary label="Чек-ин" value={latest?"Отправлен":"Не отправлен"} tone={latest?"green":"yellow"}/><Summary label="Активные задачи" value={String(openTasks.length)}/><Summary label="Обратная связь" value={String(detail.feedback.length)}/></div>
 <div className="mt-5 flex overflow-x-auto border-b border-white/10">{([['checkin','Чек-ин'],['tasks','Задачи'],['feedback','Обратная связь'],['history','История']] as const).map(([key,label])=><button type="button" key={key} onClick={()=>setTab(key)} className={`shrink-0 border-b-2 px-5 py-3 text-sm ${tab===key?'border-white text-white':'border-transparent text-white/45'}`}>{label}{key==='tasks'&&openTasks.length>0?<span className="ml-2 rounded bg-white/10 px-1.5">{openTasks.length}</span>:null}</button>)}</div>
 {error&&<p role="alert" className="mt-5 rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-red-200">{error}</p>}
 {tab==="checkin"&&<form onSubmit={submit} className="mx-auto mt-5 max-w-4xl rounded-2xl border border-white/9 p-5 sm:p-6"><h2 className="text-xl">Еженедельный чек-ин</h2><p className="mt-1 text-sm text-white/40">Расскажите трекеру, что изменилось за неделю.</p><fieldset className="mt-5"><legend className="mb-2 text-sm text-white/55">Состояние</legend><div className="grid gap-2 sm:grid-cols-3">{([['green','Всё по плану'],['yellow','Есть сложности'],['red','Нужна срочная помощь']] as const).map(([value,label])=><label key={value} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-3 text-sm ${form.health===value?'border-white/60 bg-white/[.06]':'border-white/9'}`}><input type="radio" name="health" value={value} checked={form.health===value} onChange={()=>setForm({...form,health:value})}/><span className={`size-2 rounded-full ${value==='green'?'bg-emerald-400':value==='yellow'?'bg-amber-300':'bg-red-400'}`}/>{label}</label>)}</div></fieldset><Field label="Что сделано за неделю *" value={form.summary} onChange={summary=>setForm({...form,summary})} required placeholder="Коротко опишите основные результаты"/><Field label="Следующие шаги *" value={form.nextSteps} onChange={nextSteps=>setForm({...form,nextSteps})} required placeholder="Что планируете сделать на следующей неделе"/><button type="button" onClick={()=>setExtra(v=>!v)} className="mt-4 flex w-full items-center justify-between rounded-xl border border-white/9 px-4 py-3 text-sm text-white/60">Добавить блокеры или запрос помощи <ChevronDown size={16} className={extra?'rotate-180':''}/></button>{extra&&<div className="grid gap-4 sm:grid-cols-2"><Field label="Блокеры" value={form.blockers} onChange={blockers=>setForm({...form,blockers})}/><Field label="Какая помощь нужна" value={form.helpNeeded} onChange={helpNeeded=>setForm({...form,helpNeeded})}/></div>}<div className="mt-5 flex items-center justify-between border-t border-white/8 pt-4"><span className="text-xs text-white/35">Черновик сохраняется автоматически</span><button disabled={busy==="checkin"||form.summary.trim().length<2||form.nextSteps.trim().length<2} className="workspace-button"><Send size={15}/>Отправить чек-ин</button></div></form>}
 {tab==="tasks"&&<ListEmpty empty={!detail.tasks.length} text="Активных задач нет.">{detail.tasks.map(task=><article id={`resident-tracking-${task.id}`} tabIndex={-1} key={task.id} className="flex items-start justify-between gap-4 border-b border-white/8 p-4 last:border-0"><div><p className={task.status==='done'?'text-white/35 line-through':''}>{task.title}</p>{task.description&&<p className="mt-1 text-sm text-white/40">{task.description}</p>}<p className="mt-2 text-xs text-white/30">{task.due_at?`Срок: ${new Date(task.due_at).toLocaleString('ru-RU')}`:'Без срока'} · {task.status==='open'?'В работе':task.status==='done'?'Выполнено':'Отменено'}</p></div>{task.status==='open'?<button onClick={()=>void taskStatus(task,'done')} className="overview-secondary"><Check size={14}/>Готово</button>:task.status==='done'&&<button onClick={()=>void taskStatus(task,'open')} className="text-xs text-white/40">Вернуть</button>}</article>)}</ListEmpty>}
 {tab==="feedback"&&<ListEmpty empty={!detail.feedback.length} text="Новой обратной связи пока нет.">{detail.feedback.map(row=><article key={row.id} className="border-b border-white/8 p-4 last:border-0"><p>{row.body}</p><p className="mt-2 text-xs text-white/35">{row.author.name} · {new Date(row.created_at).toLocaleString('ru-RU')}</p></article>)}</ListEmpty>}
 {tab==="history"&&<ListEmpty empty={!detail.checkins.length} text="История чек-инов пока пуста.">{detail.checkins.map(row=><article key={row.id} className="border-b border-white/8 p-4 last:border-0"><p className="text-xs text-white/35">Неделя {new Date(row.period_start).toLocaleDateString('ru-RU')}</p><p className="mt-2">{row.summary}</p><p className="mt-1 text-sm text-white/45">Дальше: {row.next_steps}</p></article>)}</ListEmpty>}
 </section>;
}
function Summary({label,value,tone}:{label:string;value:string;tone?:"green"|"yellow"}){return <div className="border-b border-white/8 p-4 last:border-0 sm:border-b-0 sm:border-r"><p className="text-xs text-white/40">{label}</p><p className={`mt-1 text-lg ${tone==='green'?'text-emerald-300':tone==='yellow'?'text-amber-200':''}`}>{value}</p></div>}
function Field({label,value,onChange,required,placeholder}:{label:string;value:string;onChange:(value:string)=>void;required?:boolean;placeholder?:string}){return <label className="mt-4 block text-sm text-white/55">{label}<textarea value={value} onChange={e=>onChange(e.target.value)} required={required} minLength={required?2:undefined} rows={3} placeholder={placeholder} className="workspace-input mt-2 resize-y"/></label>}
function ListEmpty({empty,text,children}:{empty:boolean;text:string;children:React.ReactNode}){return <div className="mx-auto mt-5 max-w-5xl overflow-hidden rounded-2xl border border-white/9">{empty?<p className="py-14 text-center text-white/35">{text}</p>:children}</div>}
