"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Download, Loader2, RefreshCw, UserRound } from "lucide-react";
import { describeApiError, getAuthJson } from "@/lib/api";

type Row = { membership_id: number; name: string; email: string; status: string; trackers: Array<{ name: string }>; program: { percent: number }; homework: { accepted: number; overdue: number; total: number }; attendance: { present: number; total: number }; last_activity_at?: string | null };
type Report = { summary: { residents: number; enrolled: number; suspended: number; completed: number; overdue_homework: number }; rows: Row[] };
const LABELS: Record<string, string> = { accepted: "Принят", enrolled: "Зачислен", suspended: "Приостановлен", completed: "Завершил", withdrawn: "Выбыл" };

export function ResidentReport({ token, cohortId, onOpenParticipant, initialQuery = "", initialStatus = "all", onFiltersChange }: { token: string; cohortId: number; canManage: boolean; onChanged: () => Promise<void>; onOpenParticipant: (id: number) => void; initialQuery?: string; initialStatus?: string; onFiltersChange?: (query: string, status: string) => void }) {
  const [report, setReport] = useState<Report | null>(null); const [query, setQuery] = useState(initialQuery); const [status, setStatus] = useState(initialStatus); const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => { setBusy("load"); setError(""); try { setReport(await getAuthJson<Report>(`/api/accelerators/cohorts/${cohortId}/report`, token)); } catch (reason) { setError(describeApiError(reason, "Не удалось загрузить отчёт")); } finally { setBusy(""); } }, [cohortId, token]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { onFiltersChange?.(query, status); }, [onFiltersChange, query, status]);
  const rows = useMemo(() => (report?.rows || []).filter((row) => (status === "all" || row.status === status) && `${row.name} ${row.email}`.toLowerCase().includes(query.trim().toLowerCase())), [query, report, status]);
  const download = async () => { setBusy("csv"); setError(""); try { const headers: Record<string, string> = { "x-pitchy-api": "1" }; if (token !== "cookie-session") headers.Authorization = `Bearer ${token}`; const response = await fetch(`/api/accelerators/cohorts/${cohortId}/report?format=csv`, { headers, credentials: "include" }); if (!response.ok) throw new Error("download_failed"); const url = URL.createObjectURL(await response.blob()); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `cohort-${cohortId}-report.csv`; anchor.click(); URL.revokeObjectURL(url); } catch (reason) { setError(describeApiError(reason, "Не удалось скачать отчёт")); } finally { setBusy(""); } };
  if (!report && busy === "load") return <div className="workspace-card grid place-items-center py-16"><Loader2 className="animate-spin text-white/40" /></div>;
  return <div className="space-y-5">
    {report && <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Всего" value={report.summary.residents} /><Metric label="Активны" value={report.summary.enrolled} /><Metric label="На паузе" value={report.summary.suspended} /><Metric label="Завершили" value={report.summary.completed} /><Metric label="Просрочено ДЗ" value={report.summary.overdue_homework} warning={report.summary.overdue_homework > 0} /></div>}
    <section className="workspace-card"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl">Участники</h2><p className="mt-1 text-sm text-white/35">Статус, трекер, задачи, рекомендации и аудит собраны в карточке участника.</p></div><div className="flex gap-2"><button type="button" onClick={() => void load()} aria-label="Обновить список" className="rounded-full border border-white/10 p-3 text-white/45"><RefreshCw size={16} /></button><button type="button" onClick={() => void download()} className="workspace-button" disabled={busy === "csv"}><Download size={15} /> CSV</button></div></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-[1fr_220px]"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Поиск по имени или email" className="workspace-input" /><select value={status} onChange={(event) => setStatus(event.target.value)} className="workspace-input"><option value="all">Все статусы</option>{Object.entries(LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>
      <div className="mt-5 overflow-x-auto"><table className="min-w-[1050px] w-full text-left text-sm"><thead className="text-xs uppercase tracking-wide text-white/30"><tr><th className="pb-3">Участник</th><th className="pb-3">Статус</th><th className="pb-3">Трекер</th><th className="pb-3">Программа</th><th className="pb-3">Домашки</th><th className="pb-3">Посещение</th><th className="pb-3">Активность</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row.membership_id} className="border-t border-white/7"><td className="py-4"><p>{row.name}</p><p className="text-xs text-white/35">{row.email}</p></td><td className="py-4">{LABELS[row.status] || row.status}</td><td className="py-4 text-white/55">{row.trackers.map((tracker) => tracker.name).join(", ") || "Не назначен"}</td><td className="py-4">{row.program.percent}%</td><td className="py-4">{row.homework.accepted}/{row.homework.total}{row.homework.overdue > 0 && <span className="ml-2 text-amber-200">−{row.homework.overdue}</span>}</td><td className="py-4">{row.attendance.present}/{row.attendance.total}</td><td className="py-4 text-white/45">{formatDate(row.last_activity_at)}</td><td className="py-4 text-right"><button type="button" onClick={() => onOpenParticipant(row.membership_id)} className="rounded-full border border-white/12 px-3 py-2 text-xs hover:border-white/30"><UserRound size={13} className="mr-1 inline" /> Карточка</button></td></tr>)}</tbody></table>{!rows.length && <p className="py-8 text-center text-sm text-white/35">По выбранным фильтрам участников нет.</p>}</div>
    </section>{error && <p role="alert" className="rounded-2xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-200">{error}</p>}
  </div>;
}
function Metric({ label, value, warning = false }: { label: string; value: number; warning?: boolean }) { return <div className={`workspace-card ${warning ? "!border-amber-400/20" : ""}`}><p className="text-2xl">{value}</p><p className="mt-1 text-xs text-white/35">{label}</p></div>; }
function formatDate(value?: string | null) { return value ? new Date(value).toLocaleDateString("ru-RU") : "—"; }
