"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { ChevronRight, Crown, Loader2, Mail, Search, Users, X } from "lucide-react";
import { describeApiError, getAuthJson, putAuthJson } from "@/lib/api";
import type { ResidentTeam } from "@/components/accelerator/TeamWorkspace";

type Tracker={user_id:number;name:string;email:string};
export function TeamManager({cohortId,token}:{cohortId:number;token:string}){
  const [teams,setTeams]=useState<ResidentTeam[]>([]);const [trackers,setTrackers]=useState<Tracker[]>([]);const [selected,setSelected]=useState<ResidentTeam|null>(null);const [query,setQuery]=useState("");const [status,setStatus]=useState<"all"|"recruiting"|"pending"|"ready">("all");const [sort,setSort]=useState<"name"|"members">("name");const [loading,setLoading]=useState(true);const [busy,setBusy]=useState("");const [error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const [teamResult,trackerRows]=await Promise.all([getAuthJson<{teams:ResidentTeam[]}>(`/api/accelerators/cohorts/${cohortId}/teams`,token),getAuthJson<Tracker[]>(`/api/accelerators/cohorts/${cohortId}/trackers`,token).catch(()=>[])]);setTeams(teamResult.teams||[]);setTrackers(trackerRows);setSelected((current)=>current?(teamResult.teams||[]).find((row)=>row.id===current.id)||null:null);}catch(reason){setError(describeApiError(reason,"Не удалось загрузить команды потока"));}finally{setLoading(false);}},[cohortId,token]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setSelected(null);};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close);},[]);
  const filtered=useMemo(()=>{const needle=query.trim().toLowerCase();return teams.filter((team)=>{const active=team.members.filter(member=>member.status==="active").length;const pending=pendingCount(team);const matchesStatus=status==="all"||(status==="recruiting"&&team.recruiting_open)||(status==="pending"&&pending>0)||(status==="ready"&&active>=team.max_members);return matchesStatus&&(!needle||[team.name,team.project?.name||"",...team.members.map((member)=>member.person.name)].some((value)=>value.toLowerCase().includes(needle)))}).sort((a,b)=>sort==="members"?b.members.filter(row=>row.status==="active").length-a.members.filter(row=>row.status==="active").length:a.name.localeCompare(b.name,"ru"));},[query,sort,status,teams]);
  const members=teams.reduce((sum,team)=>sum+team.members.filter((member)=>member.status==="active").length,0);const pending=teams.reduce((sum,team)=>sum+pendingCount(team),0);
  const assignTracker=async(value:string)=>{if(!selected||!value)return;setBusy("tracker");try{await putAuthJson(`/api/accelerators/teams/${selected.id}/tracker`,{tracker_user_id:Number(value)},token);await load();}catch(reason){setError(describeApiError(reason,"Не удалось назначить трекера команды"));}finally{setBusy("");}};
  return <section>
    <div className="flex flex-wrap items-center gap-x-7 gap-y-3 rounded-2xl border border-white/8 px-5 py-4"><Stat value={teams.length} label="команды"/><Stat value={members} label="участников"/><Stat value={pending} label="ожидают ответа" tone={pending?"yellow":undefined}/></div>
    <div className="mt-5 grid gap-3 md:grid-cols-[1fr_180px_210px]"><label className="relative block"><Search size={16} className="absolute left-4 top-1/2 -translate-y-1/2 text-white/30"/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Поиск по командам, участникам или проектам" className="workspace-input !pl-11"/></label><select value={status} onChange={event=>setStatus(event.target.value as typeof status)} className="workspace-input"><option value="all">Статус: все</option><option value="recruiting">Набор открыт</option><option value="pending">Ожидают ответа</option><option value="ready">Команда собрана</option></select><select value={sort} onChange={event=>setSort(event.target.value as typeof sort)} className="workspace-input"><option value="name">Сортировка: по названию</option><option value="members">По числу участников</option></select></div>
    {loading&&!teams.length?<div className="grid min-h-56 place-items-center"><Loader2 className="animate-spin text-white/35"/></div>:filtered.length?<div className="mt-5 overflow-hidden rounded-2xl border border-white/9">{filtered.map((team)=>{const active=team.members.filter((member)=>member.status==="active").length;return <button type="button" key={team.id} onClick={()=>setSelected(team)} className="grid w-full gap-3 border-b border-white/8 p-4 text-left last:border-0 md:grid-cols-[1.2fr_1fr_1fr_180px_auto] md:items-center"><span><span className="block text-sm font-medium">{team.name}</span><span className="block text-xs text-white/35">{team.project?.name||"Проект не привязан"}</span></span><span className="flex -space-x-2">{team.members.filter((member)=>member.status==="active").slice(0,4).map((member)=><span key={member.id} title={member.person.name} className="grid h-8 w-8 place-items-center rounded-full border border-[#1c1b1b] bg-white/10 text-[10px]">{member.person.name.split(" ").map((part)=>part[0]).join("").slice(0,2)}</span>)}</span><span className="text-sm text-white/50">{active+pendingCount(team)}/{team.max_members}</span><span className="text-sm text-white/50">{team.tracker?.name||"Трекер не назначен"}</span><ChevronRight size={16} className="text-white/30"/></button>})}</div>:<div className="py-16 text-center"><Users className="mx-auto text-white/20"/><p className="mt-4">Команд пока нет</p><p className="mt-2 text-sm text-white/35">Они появятся после создания участниками.</p></div>}
    {error&&<p role="alert" className="mt-5 rounded-xl bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}
    {selected&&<div className="fixed inset-0 z-[80] flex justify-end bg-black/65" role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget)setSelected(null);}}><aside role="dialog" aria-modal="true" aria-labelledby="team-title" className="h-full w-full max-w-xl overflow-y-auto border-l border-white/10 bg-[#1c1b1b] p-6"><div className="flex justify-between"><div><h2 id="team-title" className="text-2xl">{selected.name}</h2><p className="mt-1 text-sm text-white/40">Проект: {selected.project?.name||"не привязан"}</p></div><button type="button" onClick={()=>setSelected(null)}><X className="text-white/45"/></button></div><div className="mt-6 flex gap-2"><span className="rounded-full bg-white/7 px-3 py-1.5 text-xs"><Users size={13} className="mr-1 inline"/>{selected.members.filter((member)=>member.status==="active").length}/{selected.max_members}</span><span className={`rounded-full px-3 py-1.5 text-xs ${selected.recruiting_open?"bg-emerald-400/10 text-emerald-300":"bg-white/7 text-white/45"}`}>{selected.recruiting_open?"Набор открыт":"Набор закрыт"}</span></div><div className="my-6 border-t border-white/8"/><section><h3>Капитан</h3><div className="mt-3">{selected.members.filter((member)=>member.membership_id===selected.owner_membership_id).map((member)=><Member key={member.id} member={member} captain/>)}</div></section><section className="mt-7"><h3>Участники</h3><div className="mt-3 space-y-2">{selected.members.filter((member)=>member.membership_id!==selected.owner_membership_id&&member.status==="active").map((member)=><Member key={member.id} member={member}/>)}</div></section>{pendingCount(selected)>0&&<section className="mt-7 border-t border-white/8 pt-6"><h3>Ожидают ответа</h3><div className="mt-3 space-y-2">{selected.pending_invitations.filter((row)=>(row.status||"pending")==="pending").map((row)=><p key={row.id} className="rounded-xl border border-amber-300/15 p-3 text-sm text-amber-100">{row.invitee?.name||row.person?.name||"Приглашённый участник"}<span className="mt-1 block text-xs text-white/35">Приглашение отправлено</span></p>)}</div></section>}<section className="mt-7 border-t border-white/8 pt-5"><h3>Трекер команды</h3><p className="mt-1 text-xs text-white/35">Назначение применяется ко всей команде.</p><select value={selected.tracker?.id||""} onChange={(event)=>void assignTracker(event.target.value)} disabled={busy==="tracker"} className="workspace-input mt-3"><option value="">Не назначен</option>{trackers.map((tracker)=><option key={tracker.user_id} value={tracker.user_id}>{tracker.name}</option>)}</select></section></aside></div>}
  </section>;
}

function pendingCount(team:ResidentTeam){return team.pending_invitations.filter((row)=>(row.status||"pending")==="pending").length}
function Stat({value,label,tone}:{value:number;label:string;tone?:"yellow"}){return <p><strong className={`mr-2 text-xl ${tone?"text-amber-200":""}`}>{value}</strong><span className="text-sm text-white/45">{label}</span></p>}
function Member({member,captain}:{member:ResidentTeam["members"][number];captain?:boolean}){return <div className="rounded-xl border border-white/8 p-3"><p className="flex items-center gap-2 text-sm">{member.person.name}{captain&&<Crown size={13} className="text-amber-300"/>}</p><p className="mt-1 text-xs text-white/35">{member.title||member.role}</p>{member.person.email&&<a href={`mailto:${member.person.email}`} className="mt-2 inline-flex items-center gap-1 text-xs text-blue-200"><Mail size={11}/>{member.person.email}</a>}</div>}
