"use client";

import { useCallback, useEffect, useState } from "react";
import { Check, ChevronDown, Loader2 } from "lucide-react";

import { describeApiError, getAuthJson, patchAuthJson } from "@/lib/api";

type Event = { id: number; title: string; starts_at: string; ends_at: string; attendance_count: number };
type Resident = { membership_id: number; name: string; email: string; status: string };

export function TrackerAttendance({ cohortId, token }: { cohortId: number; token: string }) {
  const [events, setEvents] = useState<Event[]>([]); const [residents, setResidents] = useState<Record<number, Resident[]>>({}); const [openId, setOpenId] = useState<number | null>(null); const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => { try { setEvents(await getAuthJson<Event[]>(`/api/accelerators/cohorts/${cohortId}/events`, token)); } catch (reason) { setError(describeApiError(reason, "Не удалось загрузить мероприятия")); } }, [cohortId, token]);
  useEffect(() => { void load(); }, [load]);
  const open = async (eventId: number) => { if (openId === eventId) { setOpenId(null); return; } setOpenId(eventId); setBusy(`open-${eventId}`); try { const rows = await getAuthJson<Resident[]>(`/api/accelerators/events/${eventId}/attendance`, token); setResidents((current) => ({ ...current, [eventId]: rows })); } catch (reason) { setError(describeApiError(reason, "Не удалось загрузить посещаемость")); } finally { setBusy(""); } };
  const mark = async (eventId: number, membershipId: number, status: "present" | "absent" | "excused") => { setBusy(`mark-${membershipId}`); try { await patchAuthJson(`/api/accelerators/events/${eventId}/attendance`, { membership_id: membershipId, status }, token); const rows = await getAuthJson<Resident[]>(`/api/accelerators/events/${eventId}/attendance`, token); setResidents((current) => ({ ...current, [eventId]: rows })); await load(); } catch (reason) { setError(describeApiError(reason, "Не удалось сохранить отметку")); } finally { setBusy(""); } };
  return <section className="workspace-card"><h2 className="text-xl">Посещаемость моих резидентов</h2><p className="mt-1 text-sm text-white/40">Можно отмечать только назначенных вам участников.</p>{error && <p role="alert" className="mt-4 text-sm text-red-200">{error}</p>}<div className="mt-5 space-y-3">{events.map((event) => <article key={event.id} className="rounded-2xl border border-white/10 p-4"><button type="button" onClick={() => void open(event.id)} className="flex w-full items-center justify-between gap-3 text-left"><div><h3>{event.title}</h3><p className="mt-1 text-xs text-white/35">{new Date(event.starts_at).toLocaleString("ru-RU")} · присутствуют: {event.attendance_count}</p></div><ChevronDown size={16} /></button>{openId === event.id && <div className="mt-4 space-y-2 border-t border-white/8 pt-4">{busy === `open-${event.id}` ? <Loader2 className="animate-spin" /> : (residents[event.id] || []).map((resident) => <div key={resident.membership_id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-black/25 p-3"><div><p>{resident.name}</p><p className="text-xs text-white/35">{resident.email} · {resident.status === "present" ? "присутствовал" : resident.status === "absent" ? "отсутствовал" : resident.status === "excused" ? "уважительная причина" : "не отмечен"}</p></div><div className="flex gap-2"><button onClick={() => void mark(event.id, resident.membership_id, "present")} disabled={Boolean(busy)} aria-label="Присутствовал" className="rounded-full border border-white/10 p-2 text-emerald-300"><Check size={14} /></button><button onClick={() => void mark(event.id, resident.membership_id, "absent")} disabled={Boolean(busy)} className="rounded-full border border-white/10 px-3 py-1 text-xs">Нет</button><button onClick={() => void mark(event.id, resident.membership_id, "excused")} disabled={Boolean(busy)} className="rounded-full border border-white/10 px-3 py-1 text-xs">Уваж.</button></div></div>)}</div>}</article>)}{!events.length && <p className="text-sm text-white/35">Опубликованных мероприятий пока нет.</p>}</div></section>;
}
