"use client";

import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, ChevronDown, Loader2, RotateCcw } from "lucide-react";

import { describeApiError, getAuthJson, patchAuthJson } from "@/lib/api";

type Assignment = { id: number; title: string; description: string; due_at?: string | null; submission_counts: Record<string, number> };
type Submission = { id: number; resident: { name: string; email: string }; answer_text?: string | null; attachments: string[]; status: string; attempt_count: number; is_late: boolean; review_comment?: string | null };

export function TrackerHomework({ cohortId, token }: { cohortId: number; token: string }) {
  const [assignments, setAssignments] = useState<Assignment[]>([]); const [submissions, setSubmissions] = useState<Record<number, Submission[]>>({}); const [openId, setOpenId] = useState<number | null>(null); const [comments, setComments] = useState<Record<number, string>>({}); const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => { try { setAssignments(await getAuthJson<Assignment[]>(`/api/accelerators/cohorts/${cohortId}/homework`, token)); } catch (reason) { setError(describeApiError(reason, "Не удалось загрузить задания")); } }, [cohortId, token]);
  useEffect(() => { void load(); }, [load]);
  const open = async (assignmentId: number) => { if (openId === assignmentId) { setOpenId(null); return; } setOpenId(assignmentId); setBusy(`open-${assignmentId}`); try { const rows = await getAuthJson<Submission[]>(`/api/accelerators/homework/${assignmentId}/submissions`, token); setSubmissions((current) => ({ ...current, [assignmentId]: rows })); } catch (reason) { setError(describeApiError(reason, "Не удалось загрузить ответы")); } finally { setBusy(""); } };
  const review = async (assignmentId: number, submissionId: number, status: "accepted" | "needs_revision") => { setBusy(`review-${submissionId}`); try { await patchAuthJson(`/api/accelerators/homework/submissions/${submissionId}/review`, { status, comment: comments[submissionId] || null }, token); const rows = await getAuthJson<Submission[]>(`/api/accelerators/homework/${assignmentId}/submissions`, token); setSubmissions((current) => ({ ...current, [assignmentId]: rows })); await load(); } catch (reason) { setError(describeApiError(reason, "Не удалось сохранить решение")); } finally { setBusy(""); } };
  return <section className="workspace-card"><h2 className="text-xl">Ответы моих резидентов</h2><p className="mt-1 text-sm text-white/40">Доступны только назначенные вам участники.</p>{error && <p role="alert" className="mt-4 text-sm text-red-200">{error}</p>}<div className="mt-5 space-y-3">{!assignments.length ? <p className="text-sm text-white/35">Опубликованных заданий пока нет.</p> : assignments.map((assignment) => <article key={assignment.id} className="rounded-2xl border border-white/10 p-4"><button type="button" onClick={() => void open(assignment.id)} className="flex w-full items-start justify-between gap-3 text-left"><div><h3>{assignment.title}</h3><p className="mt-1 text-sm text-white/40">{assignment.description}</p><p className="mt-2 text-xs text-white/30">Ожидают проверки: {assignment.submission_counts?.submitted || 0}</p></div><ChevronDown size={16} /></button>{openId === assignment.id && <div className="mt-4 border-t border-white/8 pt-4">{busy === `open-${assignment.id}` ? <Loader2 className="animate-spin" /> : !(submissions[assignment.id] || []).length ? <p className="text-sm text-white/35">Ответов пока нет.</p> : <div className="space-y-3">{(submissions[assignment.id] || []).map((submission) => <div key={submission.id} className="rounded-xl bg-black/30 p-4"><div className="flex justify-between gap-3"><div><p>{submission.resident.name}</p><p className="text-xs text-white/35">{submission.resident.email} · попытка {submission.attempt_count}{submission.is_late ? " · с опозданием" : ""}</p></div><span className="text-xs text-white/40">{submission.status === "accepted" ? "Принято" : submission.status === "needs_revision" ? "На доработке" : "На проверке"}</span></div>{submission.answer_text && <p className="mt-3 whitespace-pre-wrap text-sm text-white/60">{submission.answer_text}</p>}{submission.attachments.map((url) => <a key={url} href={url} target="_blank" rel="noreferrer" className="mt-2 block truncate text-sm text-blue-300">{url}</a>)}{submission.status !== "accepted" && <><textarea value={comments[submission.id] || ""} onChange={(event) => setComments({ ...comments, [submission.id]: event.target.value })} placeholder="Комментарий к проверке" rows={2} className="workspace-input mt-3 resize-y" /><div className="mt-3 flex justify-end gap-2"><button onClick={() => void review(assignment.id, submission.id, "needs_revision")} disabled={Boolean(busy)} className="workspace-button !bg-transparent !text-white"><RotateCcw size={14} /> Доработать</button><button onClick={() => void review(assignment.id, submission.id, "accepted")} disabled={Boolean(busy)} className="workspace-button"><CheckCircle2 size={14} /> Принять</button></div></>}</div>)}</div>}</div>}</article>)}</div></section>;
}
