"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Loader2, Plus, Search, Trash2, UserRoundCheck, X } from "lucide-react";
import { deleteAuth, describeApiError, getAuthJson, postAuthJson } from "@/lib/api";

type Resident={membership_id:number;name:string;email:string;status:string};type Tracker={staff_id:number;user_id:number;name:string;email:string;membership_ids:number[];team_ids:number[]};type Candidate={id:number;name:string;email:string};
export function TrackerManager({token,cohortId}:{token:string;cohortId:number;residents:Resident[]}){
  const [trackers,setTrackers]=useState<Tracker[]>([]);const [candidates,setCandidates]=useState<Candidate[]>([]);const [query,setQuery]=useState("");const [open,setOpen]=useState(false);const [busy,setBusy]=useState("");const [error,setError]=useState("");
  const load=useCallback(async()=>{try{setTrackers(await getAuthJson<Tracker[]>(`/api/accelerators/cohorts/${cohortId}/trackers`,token));}catch(reason){setError(describeApiError(reason,"Не удалось загрузить трекеров"));}},[cohortId,token]);
  useEffect(()=>{void load();},[load]);useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false);};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close);},[]);
  const search=async(event:FormEvent)=>{event.preventDefault();if(query.trim().length<2)return;setBusy("search");try{setCandidates(await getAuthJson<Candidate[]>(`/api/accelerators/cohorts/${cohortId}/tracker-candidates?q=${encodeURIComponent(query.trim())}`,token));}catch(reason){setError(describeApiError(reason,"Не удалось найти пользователя"));}finally{setBusy("");}};
  const add=async(candidate:Candidate)=>{setBusy(`add-${candidate.id}`);try{await postAuthJson(`/api/accelerators/cohorts/${cohortId}/trackers`,{user_id:candidate.id,membership_ids:[]},token);setOpen(false);setCandidates([]);setQuery("");await load();}catch(reason){setError(describeApiError(reason,"Не удалось добавить трекера"));}finally{setBusy("");}};
  const remove=async(tracker:Tracker)=>{if(!window.confirm(`Убрать ${tracker.name} из команды трекеров? Назначения этого трекера будут сняты.`))return;setBusy(`remove-${tracker.user_id}`);try{await deleteAuth(`/api/accelerators/cohorts/${cohortId}/trackers/${tracker.user_id}`,token);await load();}catch(reason){setError(describeApiError(reason,"Не удалось убрать трекера"));}finally{setBusy("");}};
  return <section><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl">Пул трекеров</h2><p className="mt-1 text-sm text-white/40">Персональное назначение выполняется из карточки участника, командное — из карточки команды.</p></div><button type="button" onClick={()=>setOpen(true)} className="workspace-button"><Plus size={15}/>Добавить трекера</button></div><div className="mt-5 overflow-hidden rounded-2xl border border-white/9">{trackers.map((tracker)=><article key={tracker.user_id} className="grid gap-3 border-b border-white/8 p-4 last:border-0 md:grid-cols-[1fr_160px_160px_auto] md:items-center"><div><p>{tracker.name}</p><p className="text-xs text-white/35">{tracker.email}</p></div><p className="text-sm text-white/50">Участников: {tracker.membership_ids.length}</p><p className="text-sm text-white/50">Команд: {tracker.team_ids.length}</p><button type="button" onClick={()=>void remove(tracker)} aria-label={`Убрать ${tracker.name}`} className="rounded-xl border border-white/10 p-2 text-white/40 hover:text-red-300"><Trash2 size={15}/></button></article>)}{!trackers.length&&<div className="py-14 text-center"><UserRoundCheck className="mx-auto text-white/20"/><p className="mt-4 text-sm text-white/40">Трекеры ещё не добавлены.</p></div>}</div>{error&&<p role="alert" className="mt-5 rounded-xl bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}{open&&<div className="fixed inset-0 z-[80] grid place-items-center bg-black/70 p-4" role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget)setOpen(false);}}><div role="dialog" aria-modal="true" aria-labelledby="tracker-title" className="w-full max-w-xl rounded-2xl border border-white/10 bg-[#1c1b1b] p-6"><div className="flex justify-between"><div><h2 id="tracker-title" className="text-2xl">Добавить трекера</h2><p className="mt-1 text-sm text-white/40">Найдите пользователя по имени или email</p></div><button type="button" onClick={()=>setOpen(false)}><X className="text-white/45"/></button></div><form onSubmit={search} className="mt-5 flex gap-2"><input value={query} onChange={(event)=>setQuery(event.target.value)} minLength={2} placeholder="Имя или email" className="workspace-input"/><button className="overview-secondary" disabled={busy==="search"}>{busy==="search"?<Loader2 size={15} className="animate-spin"/>:<Search size={15}/>}Найти</button></form><div className="mt-4 space-y-2">{candidates.map((candidate)=><div key={candidate.id} className="flex items-center justify-between gap-3 rounded-xl border border-white/8 p-3"><div><p>{candidate.name}</p><p className="text-xs text-white/35">{candidate.email}</p></div><button type="button" onClick={()=>void add(candidate)} disabled={Boolean(busy)} className="workspace-button">Добавить</button></div>)}</div></div></div>}</section>;
}
