"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Loader2, Search, Trash2, UserRoundCheck } from "lucide-react";
import { deleteAuth, describeApiError, getAuthJson, postAuthJson } from "@/lib/api";

type Resident = { membership_id: number; name: string; email: string; status: string };
type Tracker = { staff_id: number; user_id: number; name: string; email: string; membership_ids: number[]; team_ids: number[] };
type Candidate = { id: number; name: string; email: string };

export function TrackerManager({ token, cohortId }: { token: string; cohortId: number; residents: Resident[] }) {
  const [trackers, setTrackers] = useState<Tracker[]>([]); const [candidates, setCandidates] = useState<Candidate[]>([]); const [query, setQuery] = useState(""); const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => { try { setTrackers(await getAuthJson<Tracker[]>(`/api/accelerators/cohorts/${cohortId}/trackers`, token)); } catch (reason) { setError(describeApiError(reason, "Не удалось загрузить трекеров")); } }, [cohortId, token]);
  useEffect(() => { void load(); setCandidates([]); }, [load]);
  const search = async (event: FormEvent) => { event.preventDefault(); if (query.trim().length < 2) return; setBusy("search"); try { setCandidates(await getAuthJson<Candidate[]>(`/api/accelerators/cohorts/${cohortId}/tracker-candidates?q=${encodeURIComponent(query.trim())}`, token)); } catch (reason) { setError(describeApiError(reason, "Не удалось найти пользователя")); } finally { setBusy(""); } };
  const add = async (candidate: Candidate) => { setBusy(`add-${candidate.id}`); try { await postAuthJson(`/api/accelerators/cohorts/${cohortId}/trackers`, { user_id: candidate.id, membership_ids: [] }, token); setCandidates([]); setQuery(""); await load(); } catch (reason) { setError(describeApiError(reason, "Не удалось добавить трекера")); } finally { setBusy(""); } };
  const remove = async (tracker: Tracker) => { if (!window.confirm(`Убрать ${tracker.name} из команды трекеров? Назначения этого трекера будут сняты.`)) return; setBusy(`remove-${tracker.user_id}`); try { await deleteAuth(`/api/accelerators/cohorts/${cohortId}/trackers/${tracker.user_id}`, token); await load(); } catch (reason) { setError(describeApiError(reason, "Не удалось убрать трекера")); } finally { setBusy(""); } };
  return <div className="space-y-6"><section className="workspace-card"><h2 className="text-xl">Команда трекеров потока</h2><p className="mt-1 text-sm text-white/40">Здесь формируется доступная команда специалистов. Персональное назначение выполняется из карточки участника, командное — из карточки команды в матчмейкинге.</p><form onSubmit={search} className="mt-5 flex gap-2"><input value={query} onChange={(event) => setQuery(event.target.value)} minLength={2} placeholder="Имя или email" className="workspace-input" /><button className="workspace-button shrink-0" disabled={busy === "search"}>{busy === "search" ? <Loader2 size={15} className="animate-spin" /> : <Search size={15} />} Найти</button></form>{candidates.length > 0 && <div className="mt-4 space-y-2">{candidates.map((candidate) => <div key={candidate.id} className="flex items-center justify-between gap-3 rounded-xl border border-white/10 p-3"><div><p>{candidate.name}</p><p className="text-xs text-white/35">{candidate.email}</p></div><button type="button" onClick={() => void add(candidate)} disabled={Boolean(busy)} className="workspace-button"><UserRoundCheck size={15} /> Добавить</button></div>)}</div>}</section><section className="workspace-card"><div className="space-y-3">{trackers.map((tracker) => <article key={tracker.user_id} className="flex items-center justify-between gap-4 rounded-2xl border border-white/10 p-4"><div><p>{tracker.name}</p><p className="mt-1 text-sm text-white/35">{tracker.email} · персонально: {tracker.membership_ids.length} · команд: {tracker.team_ids.length}</p></div><button type="button" onClick={() => void remove(tracker)} aria-label={`Убрать ${tracker.name}`} className="rounded-xl border border-white/10 p-2 text-white/40 hover:text-red-300"><Trash2 size={15} /></button></article>)}{!trackers.length && <p className="text-sm text-white/35">Трекеры ещё не добавлены.</p>}</div></section>{error && <p role="alert" className="rounded-2xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-200">{error}</p>}</div>;
}
